// Generated by scripts/fetch-juicebox-deployments.mjs — do not edit by hand.
// Source: Bananapus/deploy-all-v6@316e9d4 deployments/base_sepolia
// Addresses only (no bytecode/abi) to keep the frontend bundle small.
import type { JuiceboxDeployment } from "./types";

const data: JuiceboxDeployment = {
  chainId: 84532,
  contracts: {
    JBPermissions: {
      address: "0xf92ac1ab5a00033e35a3975739124f61928c36b0",
    },
    JBProjects: {
      address: "0x6017d1fba9dc279bfa0b03fd931c22e242ab3691",
    },
    JBDirectory: {
      address: "0x5aff29060e023e6fb87be5596652b33c65af535b",
    },
    JBSplits: {
      address: "0x28b3d11fcb8d2ad0a143c5b193cd9f2e4d43f4c3",
    },
    JBRulesets: {
      address: "0x26f2228a4e8b0079ed1c2a3d22f12ff7f83cdfba",
    },
    JBPrices: {
      address: "0xad45e4627f068d1e6b21e5301870d807543a8401",
    },
    JBTokens: {
      address: "0x1f80d8f057ee36b4c2656d107e4e4558b71ba7d9",
    },
    JBFundAccessLimits: {
      address: "0xc93360158f187fc8fc8f1062a1b31d06f185dbab",
    },
    JBFeelessAddresses: {
      address: "0x657d0e588fca6f8c49394c9ca8a1cf6505b10314",
    },
    JBTerminalStore: {
      address: "0x7497ae014a60561925b51c0a3b4ade7460b9927c",
    },
    JBMultiTerminal: {
      address: "0x130f5dd2bd8805443cf41755253d778a75a67f53",
    },
    JBController: {
      address: "0x3fcec3572e84b624477bcff4e2cf1f7deab648f1",
    },
    JBERC20: {
      address: "0x6db9cf17222d8de2012fe13b9fa5bb7981fa0b17",
    },
  },
};

export default data;
