/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GraphNode = IDL.Rec();
export const NodeId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomAttribute = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
});
export const Tag = IDL.Text;
export const Time = IDL.Int;
export const Timestamps = IDL.Record({ 'createdAt' : Time });
export const Curation = IDL.Record({
  'id' : NodeId,
  'creator' : IDL.Principal,
  'customAttributes' : IDL.Vec(CustomAttribute),
  'name' : IDL.Text,
  'timestamps' : Timestamps,
});
GraphNode.fill(
  IDL.Record({
    'id' : NodeId,
    'customAttributes' : IDL.Vec(CustomAttribute),
    'children' : IDL.Vec(GraphNode),
    'jurisdiction' : IDL.Opt(IDL.Text),
    'parentId' : IDL.Opt(NodeId),
    'tokenLabel' : IDL.Text,
    'nodeType' : IDL.Text,
  })
);
export const Directionality = IDL.Variant({
  'none' : IDL.Null,
  'bidirectional' : IDL.Null,
  'unidirectional' : IDL.Null,
});
export const GraphEdge = IDL.Record({
  'source' : NodeId,
  'directionality' : Directionality,
  'target' : NodeId,
  'edgeLabel' : IDL.Text,
});
export const Location = IDL.Record({
  'id' : NodeId,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'customAttributes' : IDL.Vec(CustomAttribute),
  'timestamps' : Timestamps,
  'parentSwarmId' : NodeId,
});
export const Swarm = IDL.Record({
  'id' : NodeId,
  'creator' : IDL.Principal,
  'customAttributes' : IDL.Vec(CustomAttribute),
  'name' : IDL.Text,
  'tags' : IDL.Vec(Tag),
  'forkSource' : IDL.Opt(NodeId),
  'timestamps' : Timestamps,
  'parentCurationId' : NodeId,
  'forkPrincipal' : IDL.Opt(IDL.Principal),
});
export const LawToken = IDL.Record({
  'id' : NodeId,
  'parentLocationId' : NodeId,
  'creator' : IDL.Principal,
  'customAttributes' : IDL.Vec(CustomAttribute),
  'timestamps' : Timestamps,
  'tokenLabel' : IDL.Text,
});
export const InterpretationToken = IDL.Record({
  'id' : NodeId,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'content' : IDL.Text,
  'customAttributes' : IDL.Vec(CustomAttribute),
  'timestamps' : Timestamps,
  'parentLawTokenId' : NodeId,
});
export const GraphData = IDL.Record({
  'curations' : IDL.Vec(Curation),
  'rootNodes' : IDL.Vec(GraphNode),
  'edges' : IDL.Vec(GraphEdge),
  'locations' : IDL.Vec(Location),
  'swarms' : IDL.Vec(Swarm),
  'lawTokens' : IDL.Vec(LawToken),
  'interpretationTokens' : IDL.Vec(InterpretationToken),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'socialUrl' : IDL.Opt(IDL.Text),
});
export const CollectibleEdition = IDL.Record({
  'tokenId' : NodeId,
  'editionNumber' : IDL.Nat,
  'owner' : IDL.Principal,
  'mintedAt' : Time,
  'tokenType' : IDL.Variant({
    'lawToken' : IDL.Null,
    'interpretationToken' : IDL.Null,
  }),
});
export const MintSettings = IDL.Record({ 'numCopies' : IDL.Nat });
export const BuzzScore = IDL.Int;
export const OwnedGraphData = IDL.Record({
  'curations' : IDL.Vec(Curation),
  'edges' : IDL.Vec(GraphEdge),
  'locations' : IDL.Vec(Location),
  'swarms' : IDL.Vec(Swarm),
  'lawTokens' : IDL.Vec(LawToken),
  'interpretationTokens' : IDL.Vec(InterpretationToken),
});
export const VoteData = IDL.Record({
  'upvotes' : IDL.Nat,
  'downvotes' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const MintCollectibleRequest = IDL.Record({
  'tokenId' : NodeId,
  'tokenType' : IDL.Variant({
    'lawToken' : IDL.Null,
    'interpretationToken' : IDL.Null,
  }),
});
export const MintCollectibleResult = IDL.Variant({
  'editionLimitReached' : IDL.Null,
  'alreadyOwned' : IDL.Null,
  'insufficientFunds' : IDL.Null,
  'success' : CollectibleEdition,
  'tokenNotFound' : IDL.Null,
});
export const SourceGraphEdgeInput = IDL.Record({
  'sourceName' : IDL.Text,
  'bidirectional' : IDL.Bool,
  'targetName' : IDL.Text,
  'edgeLabel' : IDL.Text,
});
export const SourceGraphNodeInput = IDL.Record({
  'content' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'jurisdiction' : IDL.Opt(IDL.Text),
  'attributes' : IDL.Vec(CustomAttribute),
  'parentName' : IDL.Opt(IDL.Text),
  'nodeType' : IDL.Text,
});
export const PublishSourceGraphInput = IDL.Record({
  'edges' : IDL.Vec(SourceGraphEdgeInput),
  'nodes' : IDL.Vec(SourceGraphNodeInput),
});
export const PublishResult = IDL.Variant({
  'noChanges' : IDL.Null,
  'error' : IDL.Text,
  'success' : IDL.Record({ 'message' : IDL.Text }),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'archiveNode' : IDL.Func([NodeId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCuration' : IDL.Func(
      [IDL.Text, IDL.Vec(CustomAttribute)],
      [NodeId],
      [],
    ),
  'createInterpretationToken' : IDL.Func(
      [IDL.Text, IDL.Text, NodeId, IDL.Vec(CustomAttribute)],
      [NodeId],
      [],
    ),
  'createLocation' : IDL.Func(
      [IDL.Text, IDL.Vec(CustomAttribute), NodeId],
      [NodeId],
      [],
    ),
  'createSwarm' : IDL.Func(
      [IDL.Text, IDL.Vec(Tag), NodeId, IDL.Vec(CustomAttribute)],
      [NodeId],
      [],
    ),
  'createSwarmFork' : IDL.Func([NodeId], [NodeId], []),
  'downvoteNode' : IDL.Func([NodeId], [], []),
  'getAllData' : IDL.Func([], [GraphData], ['query']),
  'getArchivedNodeIds' : IDL.Func([], [IDL.Vec(NodeId)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollectibleEditions' : IDL.Func(
      [NodeId],
      [IDL.Vec(CollectibleEdition)],
      ['query'],
    ),
  'getMintSettings' : IDL.Func([], [MintSettings], ['query']),
  'getMyBuzzBalance' : IDL.Func([], [BuzzScore], ['query']),
  'getOwnedData' : IDL.Func([], [OwnedGraphData], ['query']),
  'getSwarmForks' : IDL.Func([NodeId], [IDL.Vec(Swarm)], ['query']),
  'getSwarmMembers' : IDL.Func([NodeId], [IDL.Vec(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoteData' : IDL.Func([NodeId], [VoteData], ['query']),
  'hasUserFork' : IDL.Func([NodeId], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isNodeArchived' : IDL.Func([NodeId], [IDL.Bool], ['query']),
  'joinSwarm' : IDL.Func([NodeId], [], []),
  'leaveSwarm' : IDL.Func([NodeId], [], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'mintCollectible' : IDL.Func(
      [MintCollectibleRequest],
      [MintCollectibleResult],
      [],
    ),
  'publishSourceGraph' : IDL.Func(
      [PublishSourceGraphInput],
      [PublishResult],
      [],
    ),
  'pullFromSwarm' : IDL.Func([NodeId], [NodeId], []),
  'requestApproval' : IDL.Func([], [], []),
  'resetAllData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setMintSettings' : IDL.Func([MintSettings], [], []),
  'upvoteNode' : IDL.Func([NodeId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GraphNode = IDL.Rec();
  const NodeId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomAttribute = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const Tag = IDL.Text;
  const Time = IDL.Int;
  const Timestamps = IDL.Record({ 'createdAt' : Time });
  const Curation = IDL.Record({
    'id' : NodeId,
    'creator' : IDL.Principal,
    'customAttributes' : IDL.Vec(CustomAttribute),
    'name' : IDL.Text,
    'timestamps' : Timestamps,
  });
  GraphNode.fill(
    IDL.Record({
      'id' : NodeId,
      'customAttributes' : IDL.Vec(CustomAttribute),
      'children' : IDL.Vec(GraphNode),
      'jurisdiction' : IDL.Opt(IDL.Text),
      'parentId' : IDL.Opt(NodeId),
      'tokenLabel' : IDL.Text,
      'nodeType' : IDL.Text,
    })
  );
  const Directionality = IDL.Variant({
    'none' : IDL.Null,
    'bidirectional' : IDL.Null,
    'unidirectional' : IDL.Null,
  });
  const GraphEdge = IDL.Record({
    'source' : NodeId,
    'directionality' : Directionality,
    'target' : NodeId,
    'edgeLabel' : IDL.Text,
  });
  const Location = IDL.Record({
    'id' : NodeId,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'customAttributes' : IDL.Vec(CustomAttribute),
    'timestamps' : Timestamps,
    'parentSwarmId' : NodeId,
  });
  const Swarm = IDL.Record({
    'id' : NodeId,
    'creator' : IDL.Principal,
    'customAttributes' : IDL.Vec(CustomAttribute),
    'name' : IDL.Text,
    'tags' : IDL.Vec(Tag),
    'forkSource' : IDL.Opt(NodeId),
    'timestamps' : Timestamps,
    'parentCurationId' : NodeId,
    'forkPrincipal' : IDL.Opt(IDL.Principal),
  });
  const LawToken = IDL.Record({
    'id' : NodeId,
    'parentLocationId' : NodeId,
    'creator' : IDL.Principal,
    'customAttributes' : IDL.Vec(CustomAttribute),
    'timestamps' : Timestamps,
    'tokenLabel' : IDL.Text,
  });
  const InterpretationToken = IDL.Record({
    'id' : NodeId,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'content' : IDL.Text,
    'customAttributes' : IDL.Vec(CustomAttribute),
    'timestamps' : Timestamps,
    'parentLawTokenId' : NodeId,
  });
  const GraphData = IDL.Record({
    'curations' : IDL.Vec(Curation),
    'rootNodes' : IDL.Vec(GraphNode),
    'edges' : IDL.Vec(GraphEdge),
    'locations' : IDL.Vec(Location),
    'swarms' : IDL.Vec(Swarm),
    'lawTokens' : IDL.Vec(LawToken),
    'interpretationTokens' : IDL.Vec(InterpretationToken),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'socialUrl' : IDL.Opt(IDL.Text),
  });
  const CollectibleEdition = IDL.Record({
    'tokenId' : NodeId,
    'editionNumber' : IDL.Nat,
    'owner' : IDL.Principal,
    'mintedAt' : Time,
    'tokenType' : IDL.Variant({
      'lawToken' : IDL.Null,
      'interpretationToken' : IDL.Null,
    }),
  });
  const MintSettings = IDL.Record({ 'numCopies' : IDL.Nat });
  const BuzzScore = IDL.Int;
  const OwnedGraphData = IDL.Record({
    'curations' : IDL.Vec(Curation),
    'edges' : IDL.Vec(GraphEdge),
    'locations' : IDL.Vec(Location),
    'swarms' : IDL.Vec(Swarm),
    'lawTokens' : IDL.Vec(LawToken),
    'interpretationTokens' : IDL.Vec(InterpretationToken),
  });
  const VoteData = IDL.Record({ 'upvotes' : IDL.Nat, 'downvotes' : IDL.Nat });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const MintCollectibleRequest = IDL.Record({
    'tokenId' : NodeId,
    'tokenType' : IDL.Variant({
      'lawToken' : IDL.Null,
      'interpretationToken' : IDL.Null,
    }),
  });
  const MintCollectibleResult = IDL.Variant({
    'editionLimitReached' : IDL.Null,
    'alreadyOwned' : IDL.Null,
    'insufficientFunds' : IDL.Null,
    'success' : CollectibleEdition,
    'tokenNotFound' : IDL.Null,
  });
  const SourceGraphEdgeInput = IDL.Record({
    'sourceName' : IDL.Text,
    'bidirectional' : IDL.Bool,
    'targetName' : IDL.Text,
    'edgeLabel' : IDL.Text,
  });
  const SourceGraphNodeInput = IDL.Record({
    'content' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'jurisdiction' : IDL.Opt(IDL.Text),
    'attributes' : IDL.Vec(CustomAttribute),
    'parentName' : IDL.Opt(IDL.Text),
    'nodeType' : IDL.Text,
  });
  const PublishSourceGraphInput = IDL.Record({
    'edges' : IDL.Vec(SourceGraphEdgeInput),
    'nodes' : IDL.Vec(SourceGraphNodeInput),
  });
  const PublishResult = IDL.Variant({
    'noChanges' : IDL.Null,
    'error' : IDL.Text,
    'success' : IDL.Record({ 'message' : IDL.Text }),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'archiveNode' : IDL.Func([NodeId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCuration' : IDL.Func(
        [IDL.Text, IDL.Vec(CustomAttribute)],
        [NodeId],
        [],
      ),
    'createInterpretationToken' : IDL.Func(
        [IDL.Text, IDL.Text, NodeId, IDL.Vec(CustomAttribute)],
        [NodeId],
        [],
      ),
    'createLocation' : IDL.Func(
        [IDL.Text, IDL.Vec(CustomAttribute), NodeId],
        [NodeId],
        [],
      ),
    'createSwarm' : IDL.Func(
        [IDL.Text, IDL.Vec(Tag), NodeId, IDL.Vec(CustomAttribute)],
        [NodeId],
        [],
      ),
    'createSwarmFork' : IDL.Func([NodeId], [NodeId], []),
    'downvoteNode' : IDL.Func([NodeId], [], []),
    'getAllData' : IDL.Func([], [GraphData], ['query']),
    'getArchivedNodeIds' : IDL.Func([], [IDL.Vec(NodeId)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollectibleEditions' : IDL.Func(
        [NodeId],
        [IDL.Vec(CollectibleEdition)],
        ['query'],
      ),
    'getMintSettings' : IDL.Func([], [MintSettings], ['query']),
    'getMyBuzzBalance' : IDL.Func([], [BuzzScore], ['query']),
    'getOwnedData' : IDL.Func([], [OwnedGraphData], ['query']),
    'getSwarmForks' : IDL.Func([NodeId], [IDL.Vec(Swarm)], ['query']),
    'getSwarmMembers' : IDL.Func([NodeId], [IDL.Vec(IDL.Principal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoteData' : IDL.Func([NodeId], [VoteData], ['query']),
    'hasUserFork' : IDL.Func([NodeId], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isNodeArchived' : IDL.Func([NodeId], [IDL.Bool], ['query']),
    'joinSwarm' : IDL.Func([NodeId], [], []),
    'leaveSwarm' : IDL.Func([NodeId], [], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'mintCollectible' : IDL.Func(
        [MintCollectibleRequest],
        [MintCollectibleResult],
        [],
      ),
    'publishSourceGraph' : IDL.Func(
        [PublishSourceGraphInput],
        [PublishResult],
        [],
      ),
    'pullFromSwarm' : IDL.Func([NodeId], [NodeId], []),
    'requestApproval' : IDL.Func([], [], []),
    'resetAllData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setMintSettings' : IDL.Func([MintSettings], [], []),
    'upvoteNode' : IDL.Func([NodeId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };