/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AttributeChange {
  'key' : string,
  'newValues' : Array<string>,
  'oldValues' : Array<WeightedValue>,
  'newWeightedValues' : Array<WeightedValue>,
}
export type BuzzScore = bigint;
export interface ChatChannelSummary {
  'id' : string,
  'name' : string,
  'isSubchannel' : boolean,
  'unreadCount' : bigint,
  'parentCuration' : [] | [string],
}
export interface ChatMessage {
  'text' : string,
  'sender' : Principal,
  'timestamp' : bigint,
  'senderName' : string,
}
export interface CollectibleEdition {
  'tokenId' : NodeId,
  'editionNumber' : bigint,
  'owner' : Principal,
  'mintedAt' : Time,
  'tokenType' : { 'lawToken' : null } |
    { 'interpretationToken' : null },
}
export interface ContentVersion {
  'content' : string,
  'timestamp' : Time,
  'contributor' : Principal,
}
export interface Curation {
  'id' : NodeId,
  'creator' : Principal,
  'customAttributes' : Array<WeightedAttribute>,
  'name' : string,
  'timestamps' : Timestamps,
}
export type Directionality = { 'none' : null } |
  { 'bidirectional' : null } |
  { 'unidirectional' : null };
export interface EdgeOperation {
  'action' : { 'create' : null } |
    { 'update' : { 'newLabels' : Array<string> } },
  'labels' : Array<string>,
  'sourceId' : [] | [NodeId],
  'sourceName' : string,
  'bidirectional' : boolean,
  'targetName' : string,
  'targetId' : [] | [NodeId],
}
export interface ExtensionEntry {
  'addedNodes' : bigint,
  'addedAttributes' : bigint,
  'extendedAt' : Time,
  'addedEdges' : bigint,
}
export interface GraphData {
  'curations' : Array<Curation>,
  'rootNodes' : Array<GraphNode>,
  'edges' : Array<GraphEdge>,
  'locations' : Array<Location>,
  'swarms' : Array<Swarm>,
  'lawTokens' : Array<LawToken>,
  'interpretationTokens' : Array<InterpretationToken>,
}
export interface GraphEdge {
  'source' : NodeId,
  'directionality' : Directionality,
  'target' : NodeId,
  'edgeLabel' : string,
}
export interface GraphNode {
  'id' : NodeId,
  'customAttributes' : Array<WeightedAttribute>,
  'children' : Array<GraphNode>,
  'jurisdiction' : [] | [string],
  'parentId' : [] | [NodeId],
  'tokenLabel' : string,
  'nodeType' : string,
}
export interface InterpretationToken {
  'id' : NodeId,
  'title' : string,
  'creator' : Principal,
  'customAttributes' : Array<WeightedAttribute>,
  'timestamps' : Timestamps,
  'contentVersions' : Array<ContentVersion>,
  'parentLawTokenId' : NodeId,
}
export interface LawToken {
  'id' : NodeId,
  'parentLocationId' : NodeId,
  'creator' : Principal,
  'customAttributes' : Array<WeightedAttribute>,
  'timestamps' : Timestamps,
  'tokenLabel' : string,
}
export interface Location {
  'id' : NodeId,
  'title' : string,
  'creator' : Principal,
  'customAttributes' : Array<WeightedAttribute>,
  'timestamps' : Timestamps,
  'parentSwarmId' : NodeId,
}
export interface MintCollectibleRequest {
  'tokenId' : NodeId,
  'tokenType' : { 'lawToken' : null } |
    { 'interpretationToken' : null },
}
export type MintCollectibleResult = { 'editionLimitReached' : null } |
  { 'alreadyOwned' : null } |
  { 'insufficientFunds' : null } |
  { 'success' : CollectibleEdition } |
  { 'tokenNotFound' : null };
export interface MintSettings { 'numCopies' : bigint }
export type NodeId = string;
export interface NodeOperation {
  'localName' : string,
  'action' : { 'create' : null } |
    { 'update' : Array<AttributeChange> },
  'attributes' : Array<[string, Array<string>]>,
  'backendId' : [] | [NodeId],
  'parentName' : [] | [string],
  'nodeType' : string,
}
export interface OwnedGraphData {
  'curations' : Array<Curation>,
  'edges' : Array<GraphEdge>,
  'locations' : Array<Location>,
  'swarms' : Array<Swarm>,
  'lawTokens' : Array<LawToken>,
  'interpretationTokens' : Array<InterpretationToken>,
}
export type PublishCommitResult = {
    'error' : {
      'message' : string,
      'failedAt' : [] | [{ 'name' : string, 'nodeType' : string }],
    }
  } |
  {
    'success' : {
      'publishedSourceGraphId' : [] | [string],
      'message' : string,
      'nodeMappings' : Array<[string, NodeId]>,
    }
  };
export interface PublishPreviewResult {
  'summary' : {
    'edgesToCreate' : bigint,
    'edgesToUpdate' : bigint,
    'nodesToCreate' : bigint,
    'nodesToUpdate' : bigint,
  },
  'edgeOperations' : Array<EdgeOperation>,
  'nodeOperations' : Array<NodeOperation>,
}
export type PublishResult = { 'noChanges' : null } |
  { 'error' : string } |
  { 'success' : { 'message' : string } };
export interface PublishSourceGraphInput {
  'edges' : Array<SourceGraphEdgeInput>,
  'nodes' : Array<SourceGraphNodeInput>,
}
export interface PublishedSourceGraphMeta {
  'id' : string,
  'creator' : Principal,
  'extensionLog' : Array<ExtensionEntry>,
  'name' : string,
  'publishedAt' : Time,
  'attributeCount' : bigint,
  'creatorName' : string,
  'edgeCount' : bigint,
  'nodeCount' : bigint,
}
export interface SourceGraphEdgeInput {
  'sourceName' : string,
  'bidirectional' : boolean,
  'targetName' : string,
  'edgeLabel' : string,
}
export interface SourceGraphNodeInput {
  'id' : [] | [string],
  'content' : [] | [string],
  'name' : string,
  'tags' : Array<string>,
  'jurisdiction' : [] | [string],
  'attributes' : Array<[string, Array<string>]>,
  'parentName' : [] | [string],
  'nodeType' : string,
}
export interface Swarm {
  'id' : NodeId,
  'creator' : Principal,
  'customAttributes' : Array<WeightedAttribute>,
  'name' : string,
  'tags' : Array<Tag>,
  'forkSource' : [] | [NodeId],
  'timestamps' : Timestamps,
  'parentCurationId' : NodeId,
  'forkPrincipal' : [] | [Principal],
}
export type Tag = string;
export type Time = bigint;
export interface Timestamps { 'createdAt' : Time }
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'socialUrl' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoteData { 'upvotes' : bigint, 'downvotes' : bigint }
export interface WeightedAttribute {
  'key' : string,
  'weightedValues' : Array<WeightedValue>,
}
export interface WeightedValue { 'weight' : bigint, 'value' : string }
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'archiveNode' : ActorMethod<[NodeId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'commitPublishSourceGraph' : ActorMethod<
    [PublishSourceGraphInput, Array<[string, NodeId]>],
    PublishCommitResult
  >,
  'createCuration' : ActorMethod<[string, Array<WeightedAttribute>], NodeId>,
  'createInterpretationToken' : ActorMethod<
    [string, string, NodeId, Array<WeightedAttribute>],
    NodeId
  >,
  'createLocation' : ActorMethod<
    [string, Array<WeightedAttribute>, NodeId],
    NodeId
  >,
  'createSwarm' : ActorMethod<
    [string, Array<Tag>, NodeId, Array<WeightedAttribute>],
    NodeId
  >,
  'createSwarmFork' : ActorMethod<[NodeId], NodeId>,
  'downvoteNode' : ActorMethod<[NodeId], undefined>,
  'getAllData' : ActorMethod<[], GraphData>,
  'getAllPublishedSourceGraphs' : ActorMethod<
    [],
    Array<PublishedSourceGraphMeta>
  >,
  'getArchivedNodeIds' : ActorMethod<[], Array<NodeId>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannels' : ActorMethod<[], Array<ChatChannelSummary>>,
  'getCollectibleEditions' : ActorMethod<[NodeId], Array<CollectibleEdition>>,
  'getMessages' : ActorMethod<
    [string],
    { 'ok' : Array<ChatMessage> } |
      { 'err' : string }
  >,
  'getMintSettings' : ActorMethod<[], MintSettings>,
  'getMyBuzzBalance' : ActorMethod<[], BuzzScore>,
  'getOwnedData' : ActorMethod<[], OwnedGraphData>,
  'getPublishedSourceGraph' : ActorMethod<[string], [] | [GraphData]>,
  'getSwarmForks' : ActorMethod<[NodeId], Array<Swarm>>,
  'getSwarmMembers' : ActorMethod<[NodeId], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoteData' : ActorMethod<[NodeId], VoteData>,
  'hasUserFork' : ActorMethod<[NodeId], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isNodeArchived' : ActorMethod<[NodeId], boolean>,
  'joinSwarm' : ActorMethod<[NodeId], undefined>,
  'leaveSwarm' : ActorMethod<[NodeId], undefined>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'mintCollectible' : ActorMethod<
    [MintCollectibleRequest],
    MintCollectibleResult
  >,
  'previewPublishSourceGraph' : ActorMethod<
    [PublishSourceGraphInput, Array<[string, NodeId]>],
    PublishPreviewResult
  >,
  'publishSourceGraph' : ActorMethod<[PublishSourceGraphInput], PublishResult>,
  'pullFromSwarm' : ActorMethod<[NodeId], NodeId>,
  'requestApproval' : ActorMethod<[], undefined>,
  'resetAllData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setMintSettings' : ActorMethod<[MintSettings], undefined>,
  'upvoteNode' : ActorMethod<[NodeId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];