/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type BuzzScore = bigint;
export interface CollectibleEdition {
  'tokenId' : NodeId,
  'editionNumber' : bigint,
  'owner' : Principal,
  'mintedAt' : Time,
  'tokenType' : { 'lawToken' : null } |
    { 'interpretationToken' : null },
}
export interface Curation {
  'id' : NodeId,
  'creator' : Principal,
  'name' : string,
  'timestamps' : Timestamps,
  'jurisdiction' : string,
}
export interface CustomAttribute { 'key' : string, 'value' : string }
export type Directionality = { 'none' : null } |
  { 'bidirectional' : null } |
  { 'unidirectional' : null };
export interface GraphData {
  'curations' : Array<Curation>,
  'rootNodes' : Array<GraphNode>,
  'edges' : Array<GraphEdge>,
  'locations' : Array<Location>,
  'swarms' : Array<Swarm>,
  'sublocations' : Array<Sublocation>,
  'lawTokens' : Array<LawToken>,
  'interpretationTokens' : Array<InterpretationToken>,
}
export interface GraphEdge { 'source' : NodeId, 'target' : NodeId }
export interface GraphNode {
  'id' : NodeId,
  'children' : Array<GraphNode>,
  'jurisdiction' : [] | [string],
  'parentId' : [] | [NodeId],
  'tokenLabel' : string,
  'nodeType' : string,
}
export interface InterpretationToken {
  'id' : NodeId,
  'title' : string,
  'creator' : Principal,
  'context' : string,
  'customAttributes' : Array<CustomAttribute>,
  'toRelationshipType' : string,
  'toNodeId' : NodeId,
  'fromDirectionality' : Directionality,
  'timestamps' : Timestamps,
  'fromTokenId' : NodeId,
  'toDirectionality' : Directionality,
  'fromRelationshipType' : string,
}
export interface LawToken {
  'id' : NodeId,
  'parentLocationId' : NodeId,
  'creator' : Principal,
  'timestamps' : Timestamps,
  'tokenLabel' : string,
}
export interface Location {
  'id' : NodeId,
  'originalTokenSequence' : string,
  'title' : string,
  'creator' : Principal,
  'content' : string,
  'customAttributes' : Array<CustomAttribute>,
  'timestamps' : Timestamps,
  'parentSwarmId' : NodeId,
  'version' : bigint,
}
export interface MintCollectibleRequest {
  'tokenId' : NodeId,
  'tokenType' : { 'lawToken' : null } |
    { 'interpretationToken' : null },
}
export type MintCollectibleResult = { 'editionLimitReached' : null } |
  { 'alreadyOwned' : null } |
  { 'insufficientFunds' : null } |
  { 'success' : CollectibleEdition } |
  { 'tokenNotFound' : null };
export interface MintSettings { 'numCopies' : bigint }
export type NodeId = string;
export interface OwnedGraphData {
  'curations' : Array<Curation>,
  'edges' : Array<GraphEdge>,
  'locations' : Array<Location>,
  'swarms' : Array<Swarm>,
  'sublocations' : Array<Sublocation>,
  'lawTokens' : Array<LawToken>,
  'interpretationTokens' : Array<InterpretationToken>,
}
export interface Sublocation {
  'id' : NodeId,
  'originalTokenSequence' : string,
  'title' : string,
  'creator' : Principal,
  'content' : string,
  'timestamps' : Timestamps,
}
export interface Swarm {
  'id' : NodeId,
  'creator' : Principal,
  'name' : string,
  'tags' : Array<Tag>,
  'forkSource' : [] | [NodeId],
  'timestamps' : Timestamps,
  'parentCurationId' : NodeId,
  'forkPrincipal' : [] | [Principal],
}
export type Tag = string;
export type Time = bigint;
export interface Timestamps { 'createdAt' : Time }
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'socialUrl' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoteData { 'upvotes' : bigint, 'downvotes' : bigint }
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'archiveNode' : ActorMethod<[NodeId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCuration' : ActorMethod<[string, string], NodeId>,
  'createInterpretationToken' : ActorMethod<
    [
      string,
      string,
      NodeId,
      string,
      Directionality,
      NodeId,
      string,
      Directionality,
      Array<CustomAttribute>,
    ],
    NodeId
  >,
  'createLocation' : ActorMethod<
    [string, string, string, Array<CustomAttribute>, NodeId],
    NodeId
  >,
  'createSublocation' : ActorMethod<
    [string, string, string, Array<NodeId>],
    NodeId
  >,
  'createSwarm' : ActorMethod<[string, Array<Tag>, NodeId], NodeId>,
  'createSwarmFork' : ActorMethod<[NodeId], NodeId>,
  'downvoteNode' : ActorMethod<[NodeId], undefined>,
  'getAllData' : ActorMethod<[], GraphData>,
  'getArchivedNodeIds' : ActorMethod<[], Array<NodeId>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollectibleEditions' : ActorMethod<[NodeId], Array<CollectibleEdition>>,
  'getMintSettings' : ActorMethod<[], MintSettings>,
  'getMyBuzzBalance' : ActorMethod<[], BuzzScore>,
  'getOwnedData' : ActorMethod<[], OwnedGraphData>,
  'getSwarmForks' : ActorMethod<[NodeId], Array<Swarm>>,
  'getSwarmMembers' : ActorMethod<[NodeId], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoteData' : ActorMethod<[NodeId], VoteData>,
  'hasUserFork' : ActorMethod<[NodeId], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isNodeArchived' : ActorMethod<[NodeId], boolean>,
  'joinSwarm' : ActorMethod<[NodeId], undefined>,
  'leaveSwarm' : ActorMethod<[NodeId], undefined>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'mintCollectible' : ActorMethod<
    [MintCollectibleRequest],
    MintCollectibleResult
  >,
  'pullFromSwarm' : ActorMethod<[NodeId], NodeId>,
  'requestApproval' : ActorMethod<[], undefined>,
  'resetAllData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setMintSettings' : ActorMethod<[MintSettings], undefined>,
  'upvoteNode' : ActorMethod<[NodeId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];