/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GraphNode = IDL.Rec();
export const NodeId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SourceGraphEdgeInput = IDL.Record({
  'sourceName' : IDL.Text,
  'bidirectional' : IDL.Bool,
  'targetName' : IDL.Text,
  'edgeLabel' : IDL.Text,
});
export const SourceRef = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
export const SourceGraphNodeInput = IDL.Record({
  'id' : IDL.Opt(IDL.Text),
  'content' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'jurisdiction' : IDL.Opt(IDL.Text),
  'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text))),
  'sources' : IDL.Vec(SourceRef),
  'parentName' : IDL.Opt(IDL.Text),
  'nodeType' : IDL.Text,
});
export const PublishSourceGraphInput = IDL.Record({
  'edges' : IDL.Vec(SourceGraphEdgeInput),
  'nodes' : IDL.Vec(SourceGraphNodeInput),
});
export const PublishCommitResult = IDL.Variant({
  'error' : IDL.Record({
    'message' : IDL.Text,
    'failedAt' : IDL.Opt(
      IDL.Record({ 'name' : IDL.Text, 'nodeType' : IDL.Text })
    ),
  }),
  'success' : IDL.Record({
    'publishedSourceGraphId' : IDL.Opt(IDL.Text),
    'buzzCost' : IDL.Int,
    'message' : IDL.Text,
    'nodeMappings' : IDL.Vec(IDL.Tuple(IDL.Text, NodeId)),
  }),
});
export const WeightedValue = IDL.Record({
  'weight' : IDL.Nat,
  'value' : IDL.Text,
});
export const WeightedAttribute = IDL.Record({
  'key' : IDL.Text,
  'weightedValues' : IDL.Vec(WeightedValue),
});
export const Tag = IDL.Text;
export const Time = IDL.Int;
export const ExtensionEntry = IDL.Record({
  'addedNodes' : IDL.Nat,
  'extendedByName' : IDL.Text,
  'addedSources' : IDL.Opt(IDL.Nat),
  'addedAttributes' : IDL.Nat,
  'extendedAt' : Time,
  'extendedBy' : IDL.Principal,
  'addedHierarchyEdges' : IDL.Nat,
  'addedEdges' : IDL.Nat,
});
export const PublishedSourceGraphMeta = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'extensionLog' : IDL.Vec(ExtensionEntry),
  'name' : IDL.Text,
  'publishedAt' : Time,
  'attributeCount' : IDL.Nat,
  'creatorName' : IDL.Text,
  'edgeCount' : IDL.Nat,
  'authors' : IDL.Vec(IDL.Text),
  'sourcesCount' : IDL.Opt(IDL.Nat),
  'artworkDataUrl' : IDL.Opt(IDL.Text),
  'hierarchyEdgeCount' : IDL.Nat,
  'nodeCount' : IDL.Nat,
  'terrainParams' : IDL.Opt(IDL.Text),
});
export const BuzzScore = IDL.Int;
export const BuzzLeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'score' : BuzzScore,
  'profileName' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'socialUrl' : IDL.Opt(IDL.Text),
});
export const ChatChannelSummary = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isSubchannel' : IDL.Bool,
  'unreadCount' : IDL.Nat,
  'parentCuration' : IDL.Opt(IDL.Text),
});
export const ContributionView = IDL.Record({
  'id' : IDL.Text,
  'buzzAmount' : IDL.Int,
  'nodeId' : NodeId,
  'description' : IDL.Text,
  'payer' : IDL.Principal,
  'alreadyCredited' : IDL.Bool,
  'isFromExtension' : IDL.Bool,
  'extensionIndex' : IDL.Opt(IDL.Nat),
});
export const ChatMessage = IDL.Record({
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
});
export const TrustScore = IDL.Int;
export const CreditedContribution = IDL.Record({
  'buzzAmount' : IDL.Int,
  'contributionId' : IDL.Text,
  'description' : IDL.Text,
  'earned' : IDL.Int,
  'payer' : IDL.Principal,
  'saveCount' : IDL.Nat,
});
export const TrustTransaction = IDL.Record({
  'contributionDetails' : IDL.Vec(CreditedContribution),
  'totalBuzzCost' : IDL.Int,
  'saver' : IDL.Principal,
  'earned' : IDL.Int,
  'savedAt' : IDL.Int,
  'saveNumber' : IDL.Nat,
  'contributionIds' : IDL.Vec(IDL.Text),
});
export const Timestamps = IDL.Record({ 'createdAt' : Time });
export const Curation = IDL.Record({
  'id' : NodeId,
  'creator' : IDL.Principal,
  'customAttributes' : IDL.Vec(WeightedAttribute),
  'name' : IDL.Text,
  'timestamps' : Timestamps,
  'sources' : IDL.Vec(SourceRef),
});
GraphNode.fill(
  IDL.Record({
    'id' : NodeId,
    'customAttributes' : IDL.Vec(WeightedAttribute),
    'children' : IDL.Vec(GraphNode),
    'jurisdiction' : IDL.Opt(IDL.Text),
    'sources' : IDL.Vec(SourceRef),
    'parentId' : IDL.Opt(NodeId),
    'tokenLabel' : IDL.Text,
    'nodeType' : IDL.Text,
  })
);
export const Directionality = IDL.Variant({
  'none' : IDL.Null,
  'bidirectional' : IDL.Null,
  'unidirectional' : IDL.Null,
});
export const GraphEdge = IDL.Record({
  'source' : NodeId,
  'directionality' : Directionality,
  'target' : NodeId,
  'edgeLabel' : IDL.Text,
});
export const Location = IDL.Record({
  'id' : NodeId,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'customAttributes' : IDL.Vec(WeightedAttribute),
  'timestamps' : Timestamps,
  'parentSwarmId' : NodeId,
  'sources' : IDL.Vec(SourceRef),
});
export const Swarm = IDL.Record({
  'id' : NodeId,
  'creator' : IDL.Principal,
  'customAttributes' : IDL.Vec(WeightedAttribute),
  'name' : IDL.Text,
  'tags' : IDL.Vec(Tag),
  'forkSource' : IDL.Opt(NodeId),
  'timestamps' : Timestamps,
  'parentCurationId' : NodeId,
  'sources' : IDL.Vec(SourceRef),
  'forkPrincipal' : IDL.Opt(IDL.Principal),
});
export const LawToken = IDL.Record({
  'id' : NodeId,
  'parentLocationId' : NodeId,
  'creator' : IDL.Principal,
  'customAttributes' : IDL.Vec(WeightedAttribute),
  'timestamps' : Timestamps,
  'sources' : IDL.Vec(SourceRef),
  'tokenLabel' : IDL.Text,
});
export const ContentVersion = IDL.Record({
  'content' : IDL.Text,
  'timestamp' : Time,
  'contributor' : IDL.Principal,
});
export const InterpretationToken = IDL.Record({
  'id' : NodeId,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'customAttributes' : IDL.Vec(WeightedAttribute),
  'timestamps' : Timestamps,
  'contentVersions' : IDL.Vec(ContentVersion),
  'sources' : IDL.Vec(SourceRef),
  'parentLawTokenId' : NodeId,
});
export const GraphData = IDL.Record({
  'curations' : IDL.Vec(Curation),
  'rootNodes' : IDL.Vec(GraphNode),
  'edges' : IDL.Vec(GraphEdge),
  'locations' : IDL.Vec(Location),
  'sources' : IDL.Vec(SourceRef),
  'swarms' : IDL.Vec(Swarm),
  'lawTokens' : IDL.Vec(LawToken),
  'interpretationTokens' : IDL.Vec(InterpretationToken),
});
export const HttpRequest = IDL.Record({
  'url' : IDL.Text,
  'method' : IDL.Text,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const HttpResponse = IDL.Record({
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'status_code' : IDL.Nat16,
});
export const EdgeOperation = IDL.Record({
  'action' : IDL.Variant({
    'create' : IDL.Null,
    'update' : IDL.Record({ 'newLabels' : IDL.Vec(IDL.Text) }),
  }),
  'labels' : IDL.Vec(IDL.Text),
  'sourceId' : IDL.Opt(NodeId),
  'sourceName' : IDL.Text,
  'bidirectional' : IDL.Bool,
  'targetName' : IDL.Text,
  'targetId' : IDL.Opt(NodeId),
});
export const AttributeChange = IDL.Record({
  'key' : IDL.Text,
  'newValues' : IDL.Vec(IDL.Text),
  'oldValues' : IDL.Vec(WeightedValue),
  'newWeightedValues' : IDL.Vec(WeightedValue),
});
export const NodeOperation = IDL.Record({
  'localName' : IDL.Text,
  'action' : IDL.Variant({
    'create' : IDL.Null,
    'update' : IDL.Vec(AttributeChange),
  }),
  'sourceChanges' : IDL.Vec(SourceRef),
  'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text))),
  'backendId' : IDL.Opt(NodeId),
  'parentName' : IDL.Opt(IDL.Text),
  'nodeType' : IDL.Text,
});
export const PublishPreviewResult = IDL.Record({
  'buzzCost' : IDL.Int,
  'summary' : IDL.Record({
    'hierarchyEdgesToCreate' : IDL.Nat,
    'edgesToCreate' : IDL.Nat,
    'edgesToUpdate' : IDL.Nat,
    'attributesAdded' : IDL.Nat,
    'sourcesAdded' : IDL.Nat,
    'nodesToCreate' : IDL.Nat,
    'nodesToUpdate' : IDL.Nat,
  }),
  'edgeOperations' : IDL.Vec(EdgeOperation),
  'nodeOperations' : IDL.Vec(NodeOperation),
});
export const SaveResult = IDL.Variant({
  'ok' : IDL.Record({ 'contributions' : IDL.Vec(CreditedContribution) }),
  'err' : IDL.Text,
  'noNewTrust' : IDL.Record({ 'reason' : IDL.Text }),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'approvePluginBinding' : IDL.Func([IDL.Principal], [], []),
  'requestPluginBinding' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
  'archiveNode' : IDL.Func([NodeId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'commitPublishSourceGraph' : IDL.Func(
      [PublishSourceGraphInput, IDL.Vec(IDL.Tuple(IDL.Text, NodeId))],
      [PublishCommitResult],
      [],
    ),
  'createCuration' : IDL.Func(
      [IDL.Text, IDL.Vec(WeightedAttribute)],
      [NodeId],
      [],
    ),
  'createInterpretationToken' : IDL.Func(
      [IDL.Text, IDL.Text, NodeId, IDL.Vec(WeightedAttribute)],
      [NodeId],
      [],
    ),
  'createLocation' : IDL.Func(
      [IDL.Text, IDL.Vec(WeightedAttribute), NodeId],
      [NodeId],
      [],
    ),
  'createSwarm' : IDL.Func(
      [IDL.Text, IDL.Vec(Tag), NodeId, IDL.Vec(WeightedAttribute)],
      [NodeId],
      [],
    ),
  'ensureContributionsMigrated' : IDL.Func([IDL.Text], [], []),
  'generateApiKey' : IDL.Func([], [IDL.Text], []),
  'generateBuzzSecret' : IDL.Func([IDL.Int], [IDL.Text], []),
  'generateInviteCodes' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(IDL.Text)], []),
  'getAllPublishedSourceGraphs' : IDL.Func(
      [],
      [IDL.Vec(PublishedSourceGraphMeta)],
      ['query'],
    ),
  'getArchivedNodeIds' : IDL.Func([], [IDL.Vec(NodeId)], ['query']),
  'getBoundPluginKeys' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getBuzzLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BuzzLeaderboardEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannels' : IDL.Func([], [IDL.Vec(ChatChannelSummary)], ['query']),
  'getGraphContributions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContributionView)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(ChatMessage), 'err' : IDL.Text })],
      [],
    ),
  'getMyApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMyBuzzBalance' : IDL.Func([], [BuzzScore], ['query']),
  'getMyPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
  'getMyTrustBalance' : IDL.Func([], [TrustScore], []),
  'getMyTrustTransactions' : IDL.Func(
      [],
      [IDL.Vec(TrustTransaction)],
      ['query'],
    ),
  'getNotesData' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getPendingPluginBindings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPluginBindingStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getPublishedSourceGraph' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GraphData)],
      ['query'],
    ),
  'getTelegramConfig' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'chatId' : IDL.Text, 'botToken' : IDL.Text }))],
      [],
    ),
  'getTelegramConfigStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'updatedAt' : IDL.Opt(IDL.Nat64),
          'updatedBy' : IDL.Opt(IDL.Text),
          'hasToken' : IDL.Bool,
          'hasChatId' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasTelegramConfig' : IDL.Func([], [IDL.Bool], ['query']),
  'hasUserSavedGraph' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
  'icChallengeNonce' : IDL.Func([], [IDL.Text], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isNodeArchived' : IDL.Func([NodeId], [IDL.Bool], ['query']),
  'previewPublishSourceGraph' : IDL.Func(
      [PublishSourceGraphInput, IDL.Vec(IDL.Tuple(IDL.Text, NodeId))],
      [PublishPreviewResult],
      [],
    ),
  'redeemBuzzSecret' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'resetAllData' : IDL.Func([], [], []),
  'revokeApiKey' : IDL.Func([], [], []),
  'revokePluginBinding' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePublishedGraph' : IDL.Func(
      [IDL.Text, IDL.Vec(NodeId)],
      [SaveResult],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setTelegramConfig' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'storeNotesData' : IDL.Func([IDL.Text], [], []),
  'track_api_request' : IDL.Func([IDL.Text], [], []),
  'updateSourceGraphArtwork' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateSourceGraphTerrainParams' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GraphNode = IDL.Rec();
  const NodeId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SourceGraphEdgeInput = IDL.Record({
    'sourceName' : IDL.Text,
    'bidirectional' : IDL.Bool,
    'targetName' : IDL.Text,
    'edgeLabel' : IDL.Text,
  });
  const SourceRef = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const SourceGraphNodeInput = IDL.Record({
    'id' : IDL.Opt(IDL.Text),
    'content' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'jurisdiction' : IDL.Opt(IDL.Text),
    'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text))),
    'sources' : IDL.Vec(SourceRef),
    'parentName' : IDL.Opt(IDL.Text),
    'nodeType' : IDL.Text,
  });
  const PublishSourceGraphInput = IDL.Record({
    'edges' : IDL.Vec(SourceGraphEdgeInput),
    'nodes' : IDL.Vec(SourceGraphNodeInput),
  });
  const PublishCommitResult = IDL.Variant({
    'error' : IDL.Record({
      'message' : IDL.Text,
      'failedAt' : IDL.Opt(
        IDL.Record({ 'name' : IDL.Text, 'nodeType' : IDL.Text })
      ),
    }),
    'success' : IDL.Record({
      'publishedSourceGraphId' : IDL.Opt(IDL.Text),
      'buzzCost' : IDL.Int,
      'message' : IDL.Text,
      'nodeMappings' : IDL.Vec(IDL.Tuple(IDL.Text, NodeId)),
    }),
  });
  const WeightedValue = IDL.Record({ 'weight' : IDL.Nat, 'value' : IDL.Text });
  const WeightedAttribute = IDL.Record({
    'key' : IDL.Text,
    'weightedValues' : IDL.Vec(WeightedValue),
  });
  const Tag = IDL.Text;
  const Time = IDL.Int;
  const ExtensionEntry = IDL.Record({
    'addedNodes' : IDL.Nat,
    'extendedByName' : IDL.Text,
    'addedSources' : IDL.Opt(IDL.Nat),
    'addedAttributes' : IDL.Nat,
    'extendedAt' : Time,
    'extendedBy' : IDL.Principal,
    'addedHierarchyEdges' : IDL.Nat,
    'addedEdges' : IDL.Nat,
  });
  const PublishedSourceGraphMeta = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'extensionLog' : IDL.Vec(ExtensionEntry),
    'name' : IDL.Text,
    'publishedAt' : Time,
    'attributeCount' : IDL.Nat,
    'creatorName' : IDL.Text,
    'edgeCount' : IDL.Nat,
    'authors' : IDL.Vec(IDL.Text),
    'sourcesCount' : IDL.Opt(IDL.Nat),
    'artworkDataUrl' : IDL.Opt(IDL.Text),
    'hierarchyEdgeCount' : IDL.Nat,
    'nodeCount' : IDL.Nat,
    'terrainParams' : IDL.Opt(IDL.Text),
  });
  const BuzzScore = IDL.Int;
  const BuzzLeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'score' : BuzzScore,
    'profileName' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'socialUrl' : IDL.Opt(IDL.Text),
  });
  const ChatChannelSummary = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isSubchannel' : IDL.Bool,
    'unreadCount' : IDL.Nat,
    'parentCuration' : IDL.Opt(IDL.Text),
  });
  const ContributionView = IDL.Record({
    'id' : IDL.Text,
    'buzzAmount' : IDL.Int,
    'nodeId' : NodeId,
    'description' : IDL.Text,
    'payer' : IDL.Principal,
    'alreadyCredited' : IDL.Bool,
  });
  const ChatMessage = IDL.Record({
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
  });
  const TrustScore = IDL.Int;
  const CreditedContribution = IDL.Record({
    'buzzAmount' : IDL.Int,
    'contributionId' : IDL.Text,
    'description' : IDL.Text,
    'earned' : IDL.Int,
    'payer' : IDL.Principal,
    'saveCount' : IDL.Nat,
  });
  const TrustTransaction = IDL.Record({
    'contributionDetails' : IDL.Vec(CreditedContribution),
    'totalBuzzCost' : IDL.Int,
    'saver' : IDL.Principal,
    'earned' : IDL.Int,
    'savedAt' : IDL.Int,
    'saveNumber' : IDL.Nat,
    'contributionIds' : IDL.Vec(IDL.Text),
  });
  const Timestamps = IDL.Record({ 'createdAt' : Time });
  const Curation = IDL.Record({
    'id' : NodeId,
    'creator' : IDL.Principal,
    'customAttributes' : IDL.Vec(WeightedAttribute),
    'name' : IDL.Text,
    'timestamps' : Timestamps,
    'sources' : IDL.Vec(SourceRef),
  });
  GraphNode.fill(
    IDL.Record({
      'id' : NodeId,
      'customAttributes' : IDL.Vec(WeightedAttribute),
      'children' : IDL.Vec(GraphNode),
      'jurisdiction' : IDL.Opt(IDL.Text),
      'sources' : IDL.Vec(SourceRef),
      'parentId' : IDL.Opt(NodeId),
      'tokenLabel' : IDL.Text,
      'nodeType' : IDL.Text,
    })
  );
  const Directionality = IDL.Variant({
    'none' : IDL.Null,
    'bidirectional' : IDL.Null,
    'unidirectional' : IDL.Null,
  });
  const GraphEdge = IDL.Record({
    'source' : NodeId,
    'directionality' : Directionality,
    'target' : NodeId,
    'edgeLabel' : IDL.Text,
  });
  const Location = IDL.Record({
    'id' : NodeId,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'customAttributes' : IDL.Vec(WeightedAttribute),
    'timestamps' : Timestamps,
    'parentSwarmId' : NodeId,
    'sources' : IDL.Vec(SourceRef),
  });
  const Swarm = IDL.Record({
    'id' : NodeId,
    'creator' : IDL.Principal,
    'customAttributes' : IDL.Vec(WeightedAttribute),
    'name' : IDL.Text,
    'tags' : IDL.Vec(Tag),
    'forkSource' : IDL.Opt(NodeId),
    'timestamps' : Timestamps,
    'parentCurationId' : NodeId,
    'sources' : IDL.Vec(SourceRef),
    'forkPrincipal' : IDL.Opt(IDL.Principal),
  });
  const LawToken = IDL.Record({
    'id' : NodeId,
    'parentLocationId' : NodeId,
    'creator' : IDL.Principal,
    'customAttributes' : IDL.Vec(WeightedAttribute),
    'timestamps' : Timestamps,
    'sources' : IDL.Vec(SourceRef),
    'tokenLabel' : IDL.Text,
  });
  const ContentVersion = IDL.Record({
    'content' : IDL.Text,
    'timestamp' : Time,
    'contributor' : IDL.Principal,
  });
  const InterpretationToken = IDL.Record({
    'id' : NodeId,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'customAttributes' : IDL.Vec(WeightedAttribute),
    'timestamps' : Timestamps,
    'contentVersions' : IDL.Vec(ContentVersion),
    'sources' : IDL.Vec(SourceRef),
    'parentLawTokenId' : NodeId,
  });
  const GraphData = IDL.Record({
    'curations' : IDL.Vec(Curation),
    'rootNodes' : IDL.Vec(GraphNode),
    'edges' : IDL.Vec(GraphEdge),
    'locations' : IDL.Vec(Location),
    'sources' : IDL.Vec(SourceRef),
    'swarms' : IDL.Vec(Swarm),
    'lawTokens' : IDL.Vec(LawToken),
    'interpretationTokens' : IDL.Vec(InterpretationToken),
  });
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'status_code' : IDL.Nat16,
  });
  const EdgeOperation = IDL.Record({
    'action' : IDL.Variant({
      'create' : IDL.Null,
      'update' : IDL.Record({ 'newLabels' : IDL.Vec(IDL.Text) }),
    }),
    'labels' : IDL.Vec(IDL.Text),
    'sourceId' : IDL.Opt(NodeId),
    'sourceName' : IDL.Text,
    'bidirectional' : IDL.Bool,
    'targetName' : IDL.Text,
    'targetId' : IDL.Opt(NodeId),
  });
  const AttributeChange = IDL.Record({
    'key' : IDL.Text,
    'newValues' : IDL.Vec(IDL.Text),
    'oldValues' : IDL.Vec(WeightedValue),
    'newWeightedValues' : IDL.Vec(WeightedValue),
  });
  const NodeOperation = IDL.Record({
    'localName' : IDL.Text,
    'action' : IDL.Variant({
      'create' : IDL.Null,
      'update' : IDL.Vec(AttributeChange),
    }),
    'sourceChanges' : IDL.Vec(SourceRef),
    'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text))),
    'backendId' : IDL.Opt(NodeId),
    'parentName' : IDL.Opt(IDL.Text),
    'nodeType' : IDL.Text,
  });
  const PublishPreviewResult = IDL.Record({
    'buzzCost' : IDL.Int,
    'summary' : IDL.Record({
      'hierarchyEdgesToCreate' : IDL.Nat,
      'edgesToCreate' : IDL.Nat,
      'edgesToUpdate' : IDL.Nat,
      'attributesAdded' : IDL.Nat,
      'sourcesAdded' : IDL.Nat,
      'nodesToCreate' : IDL.Nat,
      'nodesToUpdate' : IDL.Nat,
    }),
    'edgeOperations' : IDL.Vec(EdgeOperation),
    'nodeOperations' : IDL.Vec(NodeOperation),
  });
  const SaveResult = IDL.Variant({
    'ok' : IDL.Record({ 'contributions' : IDL.Vec(CreditedContribution) }),
    'err' : IDL.Text,
    'noNewTrust' : IDL.Record({ 'reason' : IDL.Text }),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'approvePluginBinding' : IDL.Func([IDL.Principal], [], []),
  'requestPluginBinding' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
    'archiveNode' : IDL.Func([NodeId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'commitPublishSourceGraph' : IDL.Func(
        [PublishSourceGraphInput, IDL.Vec(IDL.Tuple(IDL.Text, NodeId))],
        [PublishCommitResult],
        [],
      ),
    'createCuration' : IDL.Func(
        [IDL.Text, IDL.Vec(WeightedAttribute)],
        [NodeId],
        [],
      ),
    'createInterpretationToken' : IDL.Func(
        [IDL.Text, IDL.Text, NodeId, IDL.Vec(WeightedAttribute)],
        [NodeId],
        [],
      ),
    'createLocation' : IDL.Func(
        [IDL.Text, IDL.Vec(WeightedAttribute), NodeId],
        [NodeId],
        [],
      ),
    'createSwarm' : IDL.Func(
        [IDL.Text, IDL.Vec(Tag), NodeId, IDL.Vec(WeightedAttribute)],
        [NodeId],
        [],
      ),
    'ensureContributionsMigrated' : IDL.Func([IDL.Text], [], []),
    'generateApiKey' : IDL.Func([], [IDL.Text], []),
    'generateBuzzSecret' : IDL.Func([IDL.Int], [IDL.Text], []),
    'generateInviteCodes' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'getAllPublishedSourceGraphs' : IDL.Func(
        [],
        [IDL.Vec(PublishedSourceGraphMeta)],
        ['query'],
      ),
    'getArchivedNodeIds' : IDL.Func([], [IDL.Vec(NodeId)], ['query']),
    'getBoundPluginKeys' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getBuzzLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BuzzLeaderboardEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannels' : IDL.Func([], [IDL.Vec(ChatChannelSummary)], ['query']),
    'getGraphContributions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContributionView)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(ChatMessage), 'err' : IDL.Text })],
        [],
      ),
    'getMyApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMyBuzzBalance' : IDL.Func([], [BuzzScore], ['query']),
    'getMyPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
    'getMyTrustBalance' : IDL.Func([], [TrustScore], []),
    'getMyTrustTransactions' : IDL.Func(
        [],
        [IDL.Vec(TrustTransaction)],
        ['query'],
      ),
    'getNotesData' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getPendingPluginBindings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPluginBindingStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getPublishedSourceGraph' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GraphData)],
        ['query'],
      ),
    'getTelegramConfig' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'chatId' : IDL.Text, 'botToken' : IDL.Text }))],
        [],
      ),
    'getTelegramConfigStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'updatedAt' : IDL.Opt(IDL.Nat64),
            'updatedBy' : IDL.Opt(IDL.Text),
            'hasToken' : IDL.Bool,
            'hasChatId' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasTelegramConfig' : IDL.Func([], [IDL.Bool], ['query']),
    'hasUserSavedGraph' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'icChallengeNonce' : IDL.Func([], [IDL.Text], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isNodeArchived' : IDL.Func([NodeId], [IDL.Bool], ['query']),
    'previewPublishSourceGraph' : IDL.Func(
        [PublishSourceGraphInput, IDL.Vec(IDL.Tuple(IDL.Text, NodeId))],
        [PublishPreviewResult],
        [],
      ),
    'redeemBuzzSecret' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'resetAllData' : IDL.Func([], [], []),
    'revokeApiKey' : IDL.Func([], [], []),
    'revokePluginBinding' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePublishedGraph' : IDL.Func(
        [IDL.Text, IDL.Vec(NodeId)],
        [SaveResult],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setTelegramConfig' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'storeNotesData' : IDL.Func([IDL.Text], [], []),
    'track_api_request' : IDL.Func([IDL.Text], [], []),
    'updateSourceGraphArtwork' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateSourceGraphTerrainParams' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };