/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttributeChange {
  'key' : string,
  'newValues' : Array<string>,
  'oldValues' : Array<WeightedValue>,
  'newWeightedValues' : Array<WeightedValue>,
}
export interface BuzzLeaderboardEntry {
  'principal' : Principal,
  'score' : BuzzScore,
  'profileName' : [] | [string],
}
export type BuzzScore = bigint;
export interface ChatChannelSummary {
  'id' : string,
  'name' : string,
  'isSubchannel' : boolean,
  'unreadCount' : bigint,
  'parentCuration' : [] | [string],
}
export interface ChatMessage {
  'text' : string,
  'sender' : Principal,
  'timestamp' : bigint,
  'senderName' : string,
}
export interface ContentVersion {
  'content' : string,
  'timestamp' : Time,
  'contributor' : Principal,
}
export interface ContributionView {
  'id' : string,
  'buzzAmount' : bigint,
  'nodeId' : NodeId,
  'description' : string,
  'payer' : Principal,
  'alreadyCredited' : boolean,
  'isFromExtension' : boolean,
  'extensionIndex' : [] | [bigint],
}
export interface CreditedContribution {
  'buzzAmount' : bigint,
  'contributionId' : string,
  'description' : string,
  'earned' : bigint,
  'payer' : Principal,
  'saveCount' : bigint,
}
export interface Curation {
  'id' : NodeId,
  'creator' : Principal,
  'customAttributes' : Array<WeightedAttribute>,
  'name' : string,
  'timestamps' : Timestamps,
  'sources' : Array<SourceRef>,
}
export type Directionality = { 'none' : null } |
  { 'bidirectional' : null } |
  { 'unidirectional' : null };
export interface EdgeOperation {
  'action' : { 'create' : null } |
    { 'update' : { 'newLabels' : Array<string> } },
  'labels' : Array<string>,
  'sourceId' : [] | [NodeId],
  'sourceName' : string,
  'bidirectional' : boolean,
  'targetName' : string,
  'targetId' : [] | [NodeId],
}
export interface ExtensionEntry {
  'addedNodes' : bigint,
  'extendedByName' : string,
  'addedSources' : [] | [bigint],
  'addedAttributes' : bigint,
  'extendedAt' : Time,
  'extendedBy' : Principal,
  'addedHierarchyEdges' : bigint,
  'addedEdges' : bigint,
}
export interface GraphData {
  'curations' : Array<Curation>,
  'rootNodes' : Array<GraphNode>,
  'edges' : Array<GraphEdge>,
  'locations' : Array<Location>,
  'sources' : Array<SourceRef>,
  'swarms' : Array<Swarm>,
  'lawTokens' : Array<LawToken>,
  'interpretationTokens' : Array<InterpretationToken>,
}
export interface GraphEdge {
  'source' : NodeId,
  'directionality' : Directionality,
  'target' : NodeId,
  'edgeLabel' : string,
}
export interface GraphNode {
  'id' : NodeId,
  'customAttributes' : Array<WeightedAttribute>,
  'children' : Array<GraphNode>,
  'jurisdiction' : [] | [string],
  'sources' : Array<SourceRef>,
  'parentId' : [] | [NodeId],
  'tokenLabel' : string,
  'nodeType' : string,
}
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'status_code' : number,
}
export interface InterpretationToken {
  'id' : NodeId,
  'title' : string,
  'creator' : Principal,
  'customAttributes' : Array<WeightedAttribute>,
  'timestamps' : Timestamps,
  'contentVersions' : Array<ContentVersion>,
  'sources' : Array<SourceRef>,
  'parentLawTokenId' : NodeId,
}
export interface LawToken {
  'id' : NodeId,
  'parentLocationId' : NodeId,
  'creator' : Principal,
  'customAttributes' : Array<WeightedAttribute>,
  'timestamps' : Timestamps,
  'sources' : Array<SourceRef>,
  'tokenLabel' : string,
}
export interface Location {
  'id' : NodeId,
  'title' : string,
  'creator' : Principal,
  'customAttributes' : Array<WeightedAttribute>,
  'timestamps' : Timestamps,
  'parentSwarmId' : NodeId,
  'sources' : Array<SourceRef>,
}
export type NodeId = string;
export interface NodeOperation {
  'localName' : string,
  'action' : { 'create' : null } |
    { 'update' : Array<AttributeChange> },
  'sourceChanges' : Array<SourceRef>,
  'attributes' : Array<[string, Array<string>]>,
  'backendId' : [] | [NodeId],
  'parentName' : [] | [string],
  'nodeType' : string,
}
export type PublishCommitResult = {
    'error' : {
      'message' : string,
      'failedAt' : [] | [{ 'name' : string, 'nodeType' : string }],
    }
  } |
  {
    'success' : {
      'publishedSourceGraphId' : [] | [string],
      'buzzCost' : bigint,
      'message' : string,
      'nodeMappings' : Array<[string, NodeId]>,
    }
  };
export interface PublishPreviewResult {
  'buzzCost' : bigint,
  'summary' : {
    'hierarchyEdgesToCreate' : bigint,
    'edgesToCreate' : bigint,
    'edgesToUpdate' : bigint,
    'attributesAdded' : bigint,
    'sourcesAdded' : bigint,
    'nodesToCreate' : bigint,
    'nodesToUpdate' : bigint,
  },
  'edgeOperations' : Array<EdgeOperation>,
  'nodeOperations' : Array<NodeOperation>,
}
export interface PublishSourceGraphInput {
  'edges' : Array<SourceGraphEdgeInput>,
  'nodes' : Array<SourceGraphNodeInput>,
}
export interface PublishedSourceGraphMeta {
  'id' : string,
  'creator' : Principal,
  'extensionLog' : Array<ExtensionEntry>,
  'name' : string,
  'publishedAt' : Time,
  'attributeCount' : bigint,
  'creatorName' : string,
  'edgeCount' : bigint,
  'authors' : Array<string>,
  'sourcesCount' : [] | [bigint],
  'artworkDataUrl' : [] | [string],
  'hierarchyEdgeCount' : bigint,
  'nodeCount' : bigint,
  'terrainParams' : [] | [string],
}
export type SaveResult = {
    'ok' : { 'contributions' : Array<CreditedContribution> }
  } |
  { 'err' : string } |
  { 'noNewTrust' : { 'reason' : string } };
export interface SourceGraphEdgeInput {
  'sourceName' : string,
  'bidirectional' : boolean,
  'targetName' : string,
  'edgeLabel' : string,
}
export interface SourceGraphNodeInput {
  'id' : [] | [string],
  'content' : [] | [string],
  'name' : string,
  'tags' : Array<string>,
  'jurisdiction' : [] | [string],
  'attributes' : Array<[string, Array<string>]>,
  'sources' : Array<SourceRef>,
  'parentName' : [] | [string],
  'nodeType' : string,
}
export interface SourceRef { 'url' : string, 'name' : string }
export interface Swarm {
  'id' : NodeId,
  'creator' : Principal,
  'customAttributes' : Array<WeightedAttribute>,
  'name' : string,
  'tags' : Array<Tag>,
  'forkSource' : [] | [NodeId],
  'timestamps' : Timestamps,
  'parentCurationId' : NodeId,
  'sources' : Array<SourceRef>,
  'forkPrincipal' : [] | [Principal],
}
export type Tag = string;
export type Time = bigint;
export interface Timestamps { 'createdAt' : Time }
export type TrustScore = bigint;
export interface TrustTransaction {
  'contributionDetails' : Array<CreditedContribution>,
  'totalBuzzCost' : bigint,
  'saver' : Principal,
  'earned' : bigint,
  'savedAt' : bigint,
  'saveNumber' : bigint,
  'contributionIds' : Array<string>,
}
export interface UserProfile { 'name' : string, 'socialUrl' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightedAttribute {
  'key' : string,
  'weightedValues' : Array<WeightedValue>,
}
export interface WeightedValue { 'weight' : bigint, 'value' : string }
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approvePluginBinding' : ActorMethod<[Principal], undefined>,
  'requestPluginBinding' : ActorMethod<[Principal, Principal], undefined>,
  'archiveNode' : ActorMethod<[NodeId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'commitPublishSourceGraph' : ActorMethod<
    [PublishSourceGraphInput, Array<[string, NodeId]>],
    PublishCommitResult
  >,
  'createCuration' : ActorMethod<[string, Array<WeightedAttribute>], NodeId>,
  'createInterpretationToken' : ActorMethod<
    [string, string, NodeId, Array<WeightedAttribute>],
    NodeId
  >,
  'createLocation' : ActorMethod<
    [string, Array<WeightedAttribute>, NodeId],
    NodeId
  >,
  'createSwarm' : ActorMethod<
    [string, Array<Tag>, NodeId, Array<WeightedAttribute>],
    NodeId
  >,
  'ensureContributionsMigrated' : ActorMethod<[string], undefined>,
  'generateApiKey' : ActorMethod<[], string>,
  'generateBuzzSecret' : ActorMethod<[bigint], string>,
  'generateInviteCodes' : ActorMethod<[bigint, bigint], Array<string>>,
  'getAllPublishedSourceGraphs' : ActorMethod<
    [],
    Array<PublishedSourceGraphMeta>
  >,
  'getArchivedNodeIds' : ActorMethod<[], Array<NodeId>>,
  'getBoundPluginKeys' : ActorMethod<[], Array<Principal>>,
  'getBuzzLeaderboard' : ActorMethod<[bigint], Array<BuzzLeaderboardEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannels' : ActorMethod<[], Array<ChatChannelSummary>>,
  'getGraphContributions' : ActorMethod<[string], Array<ContributionView>>,
  'getMessages' : ActorMethod<
    [string],
    { 'ok' : Array<ChatMessage> } |
      { 'err' : string }
  >,
  'getMyApiKey' : ActorMethod<[], [] | [string]>,
  'getMyBuzzBalance' : ActorMethod<[], BuzzScore>,
  'getMyPrincipal' : ActorMethod<[], Principal>,
  'getMyTrustBalance' : ActorMethod<[], TrustScore>,
  'getMyTrustTransactions' : ActorMethod<[], Array<TrustTransaction>>,
  'getNotesData' : ActorMethod<[], [] | [string]>,
  'getPendingPluginBindings' : ActorMethod<[], Array<Principal>>,
  'getPluginBindingStatus' : ActorMethod<[], boolean>,
  'getPublishedSourceGraph' : ActorMethod<[string], [] | [GraphData]>,
  'getTelegramConfig' : ActorMethod<
    [],
    [] | [{ 'chatId' : string, 'botToken' : string }]
  >,
  'getTelegramConfigStatus' : ActorMethod<
    [],
    {
      'updatedAt' : [] | [bigint],
      'updatedBy' : [] | [string],
      'hasToken' : boolean,
      'hasChatId' : boolean,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasTelegramConfig' : ActorMethod<[], boolean>,
  'hasUserSavedGraph' : ActorMethod<[string], boolean>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'icChallengeNonce' : ActorMethod<[], string>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isNodeArchived' : ActorMethod<[NodeId], boolean>,
  'previewPublishSourceGraph' : ActorMethod<
    [PublishSourceGraphInput, Array<[string, NodeId]>],
    PublishPreviewResult
  >,
  'redeemBuzzSecret' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'resetAllData' : ActorMethod<[], undefined>,
  'revokeApiKey' : ActorMethod<[], undefined>,
  'revokePluginBinding' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePublishedGraph' : ActorMethod<[string, Array<NodeId>], SaveResult>,
  'sendMessage' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setTelegramConfig' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'storeNotesData' : ActorMethod<[string], undefined>,
  'track_api_request' : ActorMethod<[string], undefined>,
  'updateSourceGraphArtwork' : ActorMethod<[string, string], boolean>,
  'updateSourceGraphTerrainParams' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];