/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NodeId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Directionality = IDL.Variant({
  'none' : IDL.Null,
  'bidirectional' : IDL.Null,
  'unidirectional' : IDL.Null,
});
export const CustomAttribute = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
});
export const Tag = IDL.Text;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'socialUrl' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const CollectibleEdition = IDL.Record({
  'tokenId' : NodeId,
  'editionNumber' : IDL.Nat,
  'owner' : IDL.Principal,
  'mintedAt' : Time,
  'tokenType' : IDL.Variant({
    'lawToken' : IDL.Null,
    'interpretationToken' : IDL.Null,
  }),
});
export const MintSettings = IDL.Record({ 'numCopies' : IDL.Nat });
export const BuzzScore = IDL.Int;
export const Timestamps = IDL.Record({ 'createdAt' : Time });
export const Swarm = IDL.Record({
  'id' : NodeId,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'tags' : IDL.Vec(Tag),
  'forkSource' : IDL.Opt(NodeId),
  'timestamps' : Timestamps,
  'parentCurationId' : NodeId,
  'forkPrincipal' : IDL.Opt(IDL.Principal),
});
export const VoteData = IDL.Record({
  'upvotes' : IDL.Nat,
  'downvotes' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const MintCollectibleRequest = IDL.Record({
  'tokenId' : NodeId,
  'tokenType' : IDL.Variant({
    'lawToken' : IDL.Null,
    'interpretationToken' : IDL.Null,
  }),
});
export const MintCollectibleResult = IDL.Variant({
  'editionLimitReached' : IDL.Null,
  'alreadyOwned' : IDL.Null,
  'insufficientFunds' : IDL.Null,
  'success' : CollectibleEdition,
  'tokenNotFound' : IDL.Null,
});

export const idlService = IDL.Service({
  'archiveNode' : IDL.Func([NodeId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCuration' : IDL.Func([IDL.Text, IDL.Text], [NodeId], []),
  'createInterpretationToken' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        NodeId,
        IDL.Text,
        Directionality,
        NodeId,
        IDL.Text,
        Directionality,
        IDL.Vec(CustomAttribute),
      ],
      [NodeId],
      [],
    ),
  'createLocation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CustomAttribute), NodeId],
      [NodeId],
      [],
    ),
  'createSublocation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(NodeId)],
      [NodeId],
      [],
    ),
  'createSwarm' : IDL.Func([IDL.Text, IDL.Vec(Tag), NodeId], [NodeId], []),
  'downvoteNode' : IDL.Func([NodeId], [], []),
  'getArchivedNodeIds' : IDL.Func([], [IDL.Vec(NodeId)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollectibleEditions' : IDL.Func(
      [NodeId],
      [IDL.Vec(CollectibleEdition)],
      ['query'],
    ),
  'getMintSettings' : IDL.Func([], [MintSettings], ['query']),
  'getMyBuzzBalance' : IDL.Func([], [BuzzScore], ['query']),
  'getSwarmForks' : IDL.Func([NodeId], [IDL.Vec(Swarm)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoteData' : IDL.Func([NodeId], [VoteData], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isNodeArchived' : IDL.Func([NodeId], [IDL.Bool], ['query']),
  'joinSwarm' : IDL.Func([NodeId], [NodeId], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'mintCollectible' : IDL.Func(
      [MintCollectibleRequest],
      [MintCollectibleResult],
      [],
    ),
  'pullFromSwarm' : IDL.Func([NodeId], [NodeId], []),
  'requestApproval' : IDL.Func([], [], []),
  'resetAllData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setMintSettings' : IDL.Func([MintSettings], [], []),
  'upvoteNode' : IDL.Func([NodeId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NodeId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Directionality = IDL.Variant({
    'none' : IDL.Null,
    'bidirectional' : IDL.Null,
    'unidirectional' : IDL.Null,
  });
  const CustomAttribute = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const Tag = IDL.Text;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'socialUrl' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const CollectibleEdition = IDL.Record({
    'tokenId' : NodeId,
    'editionNumber' : IDL.Nat,
    'owner' : IDL.Principal,
    'mintedAt' : Time,
    'tokenType' : IDL.Variant({
      'lawToken' : IDL.Null,
      'interpretationToken' : IDL.Null,
    }),
  });
  const MintSettings = IDL.Record({ 'numCopies' : IDL.Nat });
  const BuzzScore = IDL.Int;
  const Timestamps = IDL.Record({ 'createdAt' : Time });
  const Swarm = IDL.Record({
    'id' : NodeId,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'tags' : IDL.Vec(Tag),
    'forkSource' : IDL.Opt(NodeId),
    'timestamps' : Timestamps,
    'parentCurationId' : NodeId,
    'forkPrincipal' : IDL.Opt(IDL.Principal),
  });
  const VoteData = IDL.Record({ 'upvotes' : IDL.Nat, 'downvotes' : IDL.Nat });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const MintCollectibleRequest = IDL.Record({
    'tokenId' : NodeId,
    'tokenType' : IDL.Variant({
      'lawToken' : IDL.Null,
      'interpretationToken' : IDL.Null,
    }),
  });
  const MintCollectibleResult = IDL.Variant({
    'editionLimitReached' : IDL.Null,
    'alreadyOwned' : IDL.Null,
    'insufficientFunds' : IDL.Null,
    'success' : CollectibleEdition,
    'tokenNotFound' : IDL.Null,
  });
  
  return IDL.Service({
    'archiveNode' : IDL.Func([NodeId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCuration' : IDL.Func([IDL.Text, IDL.Text], [NodeId], []),
    'createInterpretationToken' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          NodeId,
          IDL.Text,
          Directionality,
          NodeId,
          IDL.Text,
          Directionality,
          IDL.Vec(CustomAttribute),
        ],
        [NodeId],
        [],
      ),
    'createLocation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CustomAttribute), NodeId],
        [NodeId],
        [],
      ),
    'createSublocation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(NodeId)],
        [NodeId],
        [],
      ),
    'createSwarm' : IDL.Func([IDL.Text, IDL.Vec(Tag), NodeId], [NodeId], []),
    'downvoteNode' : IDL.Func([NodeId], [], []),
    'getArchivedNodeIds' : IDL.Func([], [IDL.Vec(NodeId)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollectibleEditions' : IDL.Func(
        [NodeId],
        [IDL.Vec(CollectibleEdition)],
        ['query'],
      ),
    'getMintSettings' : IDL.Func([], [MintSettings], ['query']),
    'getMyBuzzBalance' : IDL.Func([], [BuzzScore], ['query']),
    'getSwarmForks' : IDL.Func([NodeId], [IDL.Vec(Swarm)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoteData' : IDL.Func([NodeId], [VoteData], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isNodeArchived' : IDL.Func([NodeId], [IDL.Bool], ['query']),
    'joinSwarm' : IDL.Func([NodeId], [NodeId], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'mintCollectible' : IDL.Func(
        [MintCollectibleRequest],
        [MintCollectibleResult],
        [],
      ),
    'pullFromSwarm' : IDL.Func([NodeId], [NodeId], []),
    'requestApproval' : IDL.Func([], [], []),
    'resetAllData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setMintSettings' : IDL.Func([MintSettings], [], []),
    'upvoteNode' : IDL.Func([NodeId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };