/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GraphNode = IDL.Rec();
export const NodeId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Directionality = IDL.Variant({
  'none' : IDL.Null,
  'bidirectional' : IDL.Null,
  'unidirectional' : IDL.Null,
});
export const CustomAttribute = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
});
export const Tag = IDL.Text;
export const BuzzScore = IDL.Int;
export const BuzzLeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'score' : BuzzScore,
  'profileName' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'socialUrl' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const CollectibleEdition = IDL.Record({
  'tokenId' : NodeId,
  'editionNumber' : IDL.Nat,
  'owner' : IDL.Principal,
  'mintedAt' : Time,
  'tokenType' : IDL.Variant({
    'lawToken' : IDL.Null,
    'interpretationToken' : IDL.Null,
  }),
});
export const Timestamps = IDL.Record({ 'createdAt' : Time });
export const Curation = IDL.Record({
  'id' : NodeId,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'timestamps' : Timestamps,
  'jurisdiction' : IDL.Text,
});
GraphNode.fill(
  IDL.Record({
    'id' : NodeId,
    'children' : IDL.Vec(GraphNode),
    'jurisdiction' : IDL.Opt(IDL.Text),
    'parentId' : IDL.Opt(NodeId),
    'tokenLabel' : IDL.Text,
    'nodeType' : IDL.Text,
  })
);
export const GraphEdge = IDL.Record({ 'source' : NodeId, 'target' : NodeId });
export const Location = IDL.Record({
  'id' : NodeId,
  'originalTokenSequence' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'content' : IDL.Text,
  'customAttributes' : IDL.Vec(CustomAttribute),
  'timestamps' : Timestamps,
  'parentSwarmId' : NodeId,
  'version' : IDL.Nat,
});
export const Swarm = IDL.Record({
  'id' : NodeId,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'tags' : IDL.Vec(Tag),
  'timestamps' : Timestamps,
  'parentCurationId' : NodeId,
});
export const LawToken = IDL.Record({
  'id' : NodeId,
  'parentLocationId' : NodeId,
  'creator' : IDL.Principal,
  'meaning' : IDL.Text,
  'timestamps' : Timestamps,
  'tokenLabel' : IDL.Text,
});
export const InterpretationToken = IDL.Record({
  'id' : NodeId,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'context' : IDL.Text,
  'customAttributes' : IDL.Vec(CustomAttribute),
  'toRelationshipType' : IDL.Text,
  'toNodeId' : NodeId,
  'fromDirectionality' : Directionality,
  'timestamps' : Timestamps,
  'fromTokenId' : NodeId,
  'toDirectionality' : Directionality,
  'fromRelationshipType' : IDL.Text,
});
export const GraphData = IDL.Record({
  'curations' : IDL.Vec(Curation),
  'rootNodes' : IDL.Vec(GraphNode),
  'edges' : IDL.Vec(GraphEdge),
  'locations' : IDL.Vec(Location),
  'swarms' : IDL.Vec(Swarm),
  'lawTokens' : IDL.Vec(LawToken),
  'interpretationTokens' : IDL.Vec(InterpretationToken),
});
export const MintSettings = IDL.Record({ 'numCopies' : IDL.Nat });
export const OwnedGraphData = IDL.Record({
  'curations' : IDL.Vec(Curation),
  'locations' : IDL.Vec(Location),
  'swarms' : IDL.Vec(Swarm),
  'lawTokens' : IDL.Vec(LawToken),
  'interpretationTokens' : IDL.Vec(InterpretationToken),
});
export const MembershipStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const MembershipInfo = IDL.Record({
  'status' : MembershipStatus,
  'principal' : IDL.Principal,
  'profileName' : IDL.Opt(IDL.Text),
});
export const SwarmUpdateStatus = IDL.Variant({
  'acted' : IDL.Null,
  'unread' : IDL.Null,
});
export const SwarmUpdate = IDL.Record({
  'status' : SwarmUpdateStatus,
  'tokenId' : NodeId,
  'userId' : IDL.Principal,
  'swarmId' : NodeId,
  'tokenTitle' : IDL.Text,
  'creatorPrincipal' : IDL.Principal,
  'timestamp' : Time,
});
export const VoteData = IDL.Record({
  'upvotes' : IDL.Nat,
  'downvotes' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const MintCollectibleRequest = IDL.Record({
  'tokenId' : NodeId,
  'tokenType' : IDL.Variant({
    'lawToken' : IDL.Null,
    'interpretationToken' : IDL.Null,
  }),
});
export const MintCollectibleResult = IDL.Variant({
  'editionLimitReached' : IDL.Null,
  'alreadyOwned' : IDL.Null,
  'insufficientFunds' : IDL.Null,
  'success' : CollectibleEdition,
  'tokenNotFound' : IDL.Null,
});

export const idlService = IDL.Service({
  'approveJoinRequest' : IDL.Func([NodeId, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCuration' : IDL.Func([IDL.Text, IDL.Text], [NodeId], []),
  'createInterpretationToken' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        NodeId,
        IDL.Text,
        Directionality,
        NodeId,
        IDL.Text,
        Directionality,
        IDL.Vec(CustomAttribute),
      ],
      [NodeId],
      [],
    ),
  'createLocation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CustomAttribute), NodeId],
      [NodeId],
      [],
    ),
  'createSwarm' : IDL.Func([IDL.Text, IDL.Vec(Tag), NodeId], [NodeId], []),
  'downvoteNode' : IDL.Func([NodeId], [], []),
  'getBuzzLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(BuzzLeaderboardEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollectibleEditions' : IDL.Func(
      [NodeId],
      [IDL.Vec(CollectibleEdition)],
      ['query'],
    ),
  'getGraphData' : IDL.Func([], [GraphData], ['query']),
  'getMintSettings' : IDL.Func([], [MintSettings], ['query']),
  'getMyBuzzBalance' : IDL.Func([], [BuzzScore], ['query']),
  'getMyOwnedGraphData' : IDL.Func([], [OwnedGraphData], ['query']),
  'getSwarmMembers' : IDL.Func([NodeId], [IDL.Vec(IDL.Principal)], ['query']),
  'getSwarmMembershipRequests' : IDL.Func(
      [NodeId],
      [IDL.Vec(MembershipInfo)],
      ['query'],
    ),
  'getSwarmUpdatesForUser' : IDL.Func(
      [NodeId],
      [IDL.Vec(SwarmUpdate)],
      ['query'],
    ),
  'getSwarmsByCreator' : IDL.Func([], [IDL.Vec(Swarm)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoteData' : IDL.Func([NodeId], [VoteData], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'mintCollectible' : IDL.Func(
      [MintCollectibleRequest],
      [MintCollectibleResult],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'requestToJoinSwarm' : IDL.Func([NodeId], [], []),
  'resetAllData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setMintSettings' : IDL.Func([MintSettings], [], []),
  'upvoteNode' : IDL.Func([NodeId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GraphNode = IDL.Rec();
  const NodeId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Directionality = IDL.Variant({
    'none' : IDL.Null,
    'bidirectional' : IDL.Null,
    'unidirectional' : IDL.Null,
  });
  const CustomAttribute = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const Tag = IDL.Text;
  const BuzzScore = IDL.Int;
  const BuzzLeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'score' : BuzzScore,
    'profileName' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'socialUrl' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const CollectibleEdition = IDL.Record({
    'tokenId' : NodeId,
    'editionNumber' : IDL.Nat,
    'owner' : IDL.Principal,
    'mintedAt' : Time,
    'tokenType' : IDL.Variant({
      'lawToken' : IDL.Null,
      'interpretationToken' : IDL.Null,
    }),
  });
  const Timestamps = IDL.Record({ 'createdAt' : Time });
  const Curation = IDL.Record({
    'id' : NodeId,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'timestamps' : Timestamps,
    'jurisdiction' : IDL.Text,
  });
  GraphNode.fill(
    IDL.Record({
      'id' : NodeId,
      'children' : IDL.Vec(GraphNode),
      'jurisdiction' : IDL.Opt(IDL.Text),
      'parentId' : IDL.Opt(NodeId),
      'tokenLabel' : IDL.Text,
      'nodeType' : IDL.Text,
    })
  );
  const GraphEdge = IDL.Record({ 'source' : NodeId, 'target' : NodeId });
  const Location = IDL.Record({
    'id' : NodeId,
    'originalTokenSequence' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'content' : IDL.Text,
    'customAttributes' : IDL.Vec(CustomAttribute),
    'timestamps' : Timestamps,
    'parentSwarmId' : NodeId,
    'version' : IDL.Nat,
  });
  const Swarm = IDL.Record({
    'id' : NodeId,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'tags' : IDL.Vec(Tag),
    'timestamps' : Timestamps,
    'parentCurationId' : NodeId,
  });
  const LawToken = IDL.Record({
    'id' : NodeId,
    'parentLocationId' : NodeId,
    'creator' : IDL.Principal,
    'meaning' : IDL.Text,
    'timestamps' : Timestamps,
    'tokenLabel' : IDL.Text,
  });
  const InterpretationToken = IDL.Record({
    'id' : NodeId,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'context' : IDL.Text,
    'customAttributes' : IDL.Vec(CustomAttribute),
    'toRelationshipType' : IDL.Text,
    'toNodeId' : NodeId,
    'fromDirectionality' : Directionality,
    'timestamps' : Timestamps,
    'fromTokenId' : NodeId,
    'toDirectionality' : Directionality,
    'fromRelationshipType' : IDL.Text,
  });
  const GraphData = IDL.Record({
    'curations' : IDL.Vec(Curation),
    'rootNodes' : IDL.Vec(GraphNode),
    'edges' : IDL.Vec(GraphEdge),
    'locations' : IDL.Vec(Location),
    'swarms' : IDL.Vec(Swarm),
    'lawTokens' : IDL.Vec(LawToken),
    'interpretationTokens' : IDL.Vec(InterpretationToken),
  });
  const MintSettings = IDL.Record({ 'numCopies' : IDL.Nat });
  const OwnedGraphData = IDL.Record({
    'curations' : IDL.Vec(Curation),
    'locations' : IDL.Vec(Location),
    'swarms' : IDL.Vec(Swarm),
    'lawTokens' : IDL.Vec(LawToken),
    'interpretationTokens' : IDL.Vec(InterpretationToken),
  });
  const MembershipStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const MembershipInfo = IDL.Record({
    'status' : MembershipStatus,
    'principal' : IDL.Principal,
    'profileName' : IDL.Opt(IDL.Text),
  });
  const SwarmUpdateStatus = IDL.Variant({
    'acted' : IDL.Null,
    'unread' : IDL.Null,
  });
  const SwarmUpdate = IDL.Record({
    'status' : SwarmUpdateStatus,
    'tokenId' : NodeId,
    'userId' : IDL.Principal,
    'swarmId' : NodeId,
    'tokenTitle' : IDL.Text,
    'creatorPrincipal' : IDL.Principal,
    'timestamp' : Time,
  });
  const VoteData = IDL.Record({ 'upvotes' : IDL.Nat, 'downvotes' : IDL.Nat });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const MintCollectibleRequest = IDL.Record({
    'tokenId' : NodeId,
    'tokenType' : IDL.Variant({
      'lawToken' : IDL.Null,
      'interpretationToken' : IDL.Null,
    }),
  });
  const MintCollectibleResult = IDL.Variant({
    'editionLimitReached' : IDL.Null,
    'alreadyOwned' : IDL.Null,
    'insufficientFunds' : IDL.Null,
    'success' : CollectibleEdition,
    'tokenNotFound' : IDL.Null,
  });
  
  return IDL.Service({
    'approveJoinRequest' : IDL.Func([NodeId, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCuration' : IDL.Func([IDL.Text, IDL.Text], [NodeId], []),
    'createInterpretationToken' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          NodeId,
          IDL.Text,
          Directionality,
          NodeId,
          IDL.Text,
          Directionality,
          IDL.Vec(CustomAttribute),
        ],
        [NodeId],
        [],
      ),
    'createLocation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CustomAttribute), NodeId],
        [NodeId],
        [],
      ),
    'createSwarm' : IDL.Func([IDL.Text, IDL.Vec(Tag), NodeId], [NodeId], []),
    'downvoteNode' : IDL.Func([NodeId], [], []),
    'getBuzzLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(BuzzLeaderboardEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollectibleEditions' : IDL.Func(
        [NodeId],
        [IDL.Vec(CollectibleEdition)],
        ['query'],
      ),
    'getGraphData' : IDL.Func([], [GraphData], ['query']),
    'getMintSettings' : IDL.Func([], [MintSettings], ['query']),
    'getMyBuzzBalance' : IDL.Func([], [BuzzScore], ['query']),
    'getMyOwnedGraphData' : IDL.Func([], [OwnedGraphData], ['query']),
    'getSwarmMembers' : IDL.Func([NodeId], [IDL.Vec(IDL.Principal)], ['query']),
    'getSwarmMembershipRequests' : IDL.Func(
        [NodeId],
        [IDL.Vec(MembershipInfo)],
        ['query'],
      ),
    'getSwarmUpdatesForUser' : IDL.Func(
        [NodeId],
        [IDL.Vec(SwarmUpdate)],
        ['query'],
      ),
    'getSwarmsByCreator' : IDL.Func([], [IDL.Vec(Swarm)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoteData' : IDL.Func([NodeId], [VoteData], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'mintCollectible' : IDL.Func(
        [MintCollectibleRequest],
        [MintCollectibleResult],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'requestToJoinSwarm' : IDL.Func([NodeId], [], []),
    'resetAllData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setMintSettings' : IDL.Func([MintSettings], [], []),
    'upvoteNode' : IDL.Func([NodeId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };