/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type MintCollectibleResult = {
    __kind__: "editionLimitReached";
    editionLimitReached: null;
} | {
    __kind__: "alreadyOwned";
    alreadyOwned: null;
} | {
    __kind__: "insufficientFunds";
    insufficientFunds: null;
} | {
    __kind__: "success";
    success: CollectibleEdition;
} | {
    __kind__: "tokenNotFound";
    tokenNotFound: null;
};
export type NodeId = string;
export type Time = bigint;
export interface VoteData {
    upvotes: bigint;
    downvotes: bigint;
}
export interface Timestamps {
    createdAt: Time;
}
export interface MintSettings {
    numCopies: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export type Tag = string;
export interface MintCollectibleRequest {
    tokenId: NodeId;
    tokenType: Variant_lawToken_interpretationToken;
}
export interface CollectibleEdition {
    tokenId: NodeId;
    editionNumber: bigint;
    owner: Principal;
    mintedAt: Time;
    tokenType: Variant_lawToken_interpretationToken;
}
export interface CustomAttribute {
    key: string;
    value: string;
}
export interface Swarm {
    id: NodeId;
    creator: Principal;
    name: string;
    tags: Array<Tag>;
    forkSource?: NodeId;
    timestamps: Timestamps;
    parentCurationId: NodeId;
    forkPrincipal?: Principal;
}
export type BuzzScore = bigint;
export interface UserProfile {
    name: string;
    socialUrl?: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Directionality {
    none = "none",
    bidirectional = "bidirectional",
    unidirectional = "unidirectional"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_lawToken_interpretationToken {
    lawToken = "lawToken",
    interpretationToken = "interpretationToken"
}
export interface GraphNode {
    id: NodeId;
    nodeType: string;
    tokenLabel: string;
    jurisdiction?: string;
    parentId?: NodeId;
    children: GraphNode[];
}
export interface GraphEdge {
    source: NodeId;
    target: NodeId;
}
export interface OwnedGraphData {
    curations: Array<Curation>;
    swarms: Array<Swarm>;
    locations: Array<Location>;
    lawTokens: Array<LawToken>;
    interpretationTokens: Array<InterpretationToken>;
    sublocations?: Array<Sublocation>;
    edges?: Array<GraphEdge>;
}
export interface GraphData {
    curations: Array<Curation>;
    swarms: Array<Swarm>;
    locations: Array<Location>;
    lawTokens: Array<LawToken>;
    interpretationTokens: Array<InterpretationToken>;
    sublocations: Array<Sublocation>;
    rootNodes: Array<GraphNode>;
    edges: Array<GraphEdge>;
}
export interface Curation {
    id: NodeId;
    name: string;
    jurisdiction: string;
    creator: Principal;
    timestamps: Timestamps;
}
export interface Location {
    id: NodeId;
    title: string;
    content: string;
    originalTokenSequence: string;
    customAttributes: Array<CustomAttribute>;
    parentSwarmId: NodeId;
    creator: Principal;
    version: number;
    timestamps: Timestamps;
}
export interface LawToken {
    id: NodeId;
    tokenLabel: string;
    parentLocationId: NodeId;
    creator: Principal;
    timestamps: Timestamps;
}
export interface Sublocation {
    id: NodeId;
    title: string;
    content: string;
    originalTokenSequence: string;
    creator: Principal;
    timestamps: Timestamps;
}
export interface InterpretationToken {
    id: NodeId;
    title: string;
    context: string;
    fromTokenId: NodeId;
    fromRelationshipType: string;
    fromDirectionality: Directionality;
    toNodeId: NodeId;
    toRelationshipType: string;
    toDirectionality: Directionality;
    customAttributes: Array<CustomAttribute>;
    creator: Principal;
    timestamps: Timestamps;
}

export interface backendInterface {
    archiveNode(nodeId: NodeId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCuration(name: string, jurisdiction: string): Promise<NodeId>;
    createInterpretationToken(title: string, context: string, fromTokenId: NodeId, fromRelationshipType: string, fromDirectionality: Directionality, toNodeId: NodeId, toRelationshipType: string, toDirectionality: Directionality, customAttributes: Array<CustomAttribute>): Promise<NodeId>;
    createLocation(title: string, content: string, originalTokenSequence: string, customAttributes: Array<CustomAttribute>, parentSwarmId: NodeId): Promise<NodeId>;
    createSublocation(title: string, content: string, originalTokenSequence: string, parentLawTokenIds: Array<NodeId>): Promise<NodeId>;
    createSwarm(name: string, tags: Array<Tag>, parentCurationId: NodeId): Promise<NodeId>;
    downvoteNode(nodeId: NodeId): Promise<void>;
    getArchivedNodeIds(): Promise<Array<NodeId>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCollectibleEditions(tokenId: NodeId): Promise<Array<CollectibleEdition>>;
    getAllData(): Promise<GraphData>;
    getLeaderboard(): Promise<Array<{ principal: Principal; score: bigint }>>;
    getMintSettings(): Promise<MintSettings>;
    getOwnedData(): Promise<OwnedGraphData>;
    getSwarmMembers(swarmId: NodeId): Promise<Array<Principal>>;
    getMyBuzzBalance(): Promise<BuzzScore>;
    getSwarmForks(swarmId: NodeId): Promise<Array<Swarm>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVoteData(nodeId: NodeId): Promise<VoteData>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isNodeArchived(nodeId: NodeId): Promise<boolean>;
    joinSwarm(swarmId: NodeId): Promise<NodeId>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    mintCollectible(request: MintCollectibleRequest): Promise<MintCollectibleResult>;
    pullFromSwarm(targetSwarmId: NodeId): Promise<NodeId>;
    requestApproval(): Promise<void>;
    resetAllData(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setMintSettings(settings: MintSettings): Promise<void>;
    upvoteNode(nodeId: NodeId): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, CollectibleEdition as _CollectibleEdition, Directionality as _Directionality, MintCollectibleRequest as _MintCollectibleRequest, MintCollectibleResult as _MintCollectibleResult, NodeId as _NodeId, Swarm as _Swarm, Tag as _Tag, Time as _Time, Timestamps as _Timestamps, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async archiveNode(arg0: NodeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveNode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveNode(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCuration(arg0: string, arg1: string): Promise<NodeId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCuration(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCuration(arg0, arg1);
            return result;
        }
    }
    async createInterpretationToken(arg0: string, arg1: string, arg2: NodeId, arg3: string, arg4: Directionality, arg5: NodeId, arg6: string, arg7: Directionality, arg8: Array<CustomAttribute>): Promise<NodeId> {
        if (this.processError) {
            try {
                const result = await this.actor.createInterpretationToken(arg0, arg1, arg2, arg3, to_candid_Directionality_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_Directionality_n3(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInterpretationToken(arg0, arg1, arg2, arg3, to_candid_Directionality_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_Directionality_n3(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
    async createLocation(arg0: string, arg1: string, arg2: string, arg3: Array<CustomAttribute>, arg4: NodeId): Promise<NodeId> {
        if (this.processError) {
            try {
                const result = await this.actor.createLocation(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLocation(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createSublocation(arg0: string, arg1: string, arg2: string, arg3: Array<NodeId>): Promise<NodeId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSublocation(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSublocation(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createSwarm(arg0: string, arg1: Array<Tag>, arg2: NodeId): Promise<NodeId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSwarm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSwarm(arg0, arg1, arg2);
            return result;
        }
    }
    async downvoteNode(arg0: NodeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.downvoteNode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downvoteNode(arg0);
            return result;
        }
    }
    async getArchivedNodeIds(): Promise<Array<NodeId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArchivedNodeIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArchivedNodeIds();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollectibleEditions(arg0: NodeId): Promise<Array<CollectibleEdition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectibleEditions(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectibleEditions(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMintSettings(): Promise<MintSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getMintSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMintSettings();
            return result;
        }
    }
    async getMyBuzzBalance(): Promise<BuzzScore> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBuzzBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBuzzBalance();
            return result;
        }
    }
    async getSwarmForks(arg0: NodeId): Promise<Array<Swarm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSwarmForks(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSwarmForks(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoteData(arg0: NodeId): Promise<VoteData> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoteData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoteData(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isNodeArchived(arg0: NodeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isNodeArchived(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isNodeArchived(arg0);
            return result;
        }
    }
    async joinSwarm(arg0: NodeId): Promise<NodeId> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSwarm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSwarm(arg0);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async mintCollectible(arg0: MintCollectibleRequest): Promise<MintCollectibleResult> {
        if (this.processError) {
            try {
                const result = await this.actor.mintCollectible(to_candid_MintCollectibleRequest_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MintCollectibleResult_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintCollectible(to_candid_MintCollectibleRequest_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MintCollectibleResult_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async pullFromSwarm(arg0: NodeId): Promise<NodeId> {
        if (this.processError) {
            try {
                const result = await this.actor.pullFromSwarm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pullFromSwarm(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async resetAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllData();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setMintSettings(arg0: MintSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMintSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMintSettings(arg0);
            return result;
        }
    }
    async getAllData(): Promise<GraphData> {
        const result = await this.actor.getAllData();
        return result as unknown as GraphData;
    }
    async getOwnedData(): Promise<OwnedGraphData> {
        const result = await this.actor.getOwnedData();
        return result as unknown as OwnedGraphData;
    }
    async getSwarmMembers(arg0: NodeId): Promise<Array<Principal>> {
        const result = await this.actor.getSwarmMembers(arg0);
        return result;
    }
    async getLeaderboard(): Promise<Array<{ principal: Principal; score: bigint }>> {
        const result = await this.actor.getLeaderboard();
        return result as unknown as Array<{ principal: Principal; score: bigint }>;
    }
    async upvoteNode(arg0: NodeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upvoteNode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upvoteNode(arg0);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_CollectibleEdition_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectibleEdition): CollectibleEdition {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_MintCollectibleResult_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MintCollectibleResult): MintCollectibleResult {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Swarm_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Swarm): Swarm {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NodeId]): NodeId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tokenId: _NodeId;
    editionNumber: bigint;
    owner: Principal;
    mintedAt: _Time;
    tokenType: {
        lawToken: null;
    } | {
        interpretationToken: null;
    };
}): {
    tokenId: NodeId;
    editionNumber: bigint;
    owner: Principal;
    mintedAt: Time;
    tokenType: Variant_lawToken_interpretationToken;
} {
    return {
        tokenId: value.tokenId,
        editionNumber: value.editionNumber,
        owner: value.owner,
        mintedAt: value.mintedAt,
        tokenType: from_candid_variant_n14(_uploadFile, _downloadFile, value.tokenType)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NodeId;
    creator: Principal;
    name: string;
    tags: Array<_Tag>;
    forkSource: [] | [_NodeId];
    timestamps: _Timestamps;
    parentCurationId: _NodeId;
    forkPrincipal: [] | [Principal];
}): {
    id: NodeId;
    creator: Principal;
    name: string;
    tags: Array<Tag>;
    forkSource?: NodeId;
    timestamps: Timestamps;
    parentCurationId: NodeId;
    forkPrincipal?: Principal;
} {
    return {
        id: value.id,
        creator: value.creator,
        name: value.name,
        tags: value.tags,
        forkSource: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.forkSource)),
        timestamps: value.timestamps,
        parentCurationId: value.parentCurationId,
        forkPrincipal: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.forkPrincipal))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n23(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    socialUrl: [] | [string];
}): {
    name: string;
    socialUrl?: string;
} {
    return {
        name: value.name,
        socialUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.socialUrl))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lawToken: null;
} | {
    interpretationToken: null;
}): Variant_lawToken_interpretationToken {
    return "lawToken" in value ? Variant_lawToken_interpretationToken.lawToken : "interpretationToken" in value ? Variant_lawToken_interpretationToken.interpretationToken : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    editionLimitReached: null;
} | {
    alreadyOwned: null;
} | {
    insufficientFunds: null;
} | {
    success: _CollectibleEdition;
} | {
    tokenNotFound: null;
}): {
    __kind__: "editionLimitReached";
    editionLimitReached: null;
} | {
    __kind__: "alreadyOwned";
    alreadyOwned: null;
} | {
    __kind__: "insufficientFunds";
    insufficientFunds: null;
} | {
    __kind__: "success";
    success: CollectibleEdition;
} | {
    __kind__: "tokenNotFound";
    tokenNotFound: null;
} {
    return "editionLimitReached" in value ? {
        __kind__: "editionLimitReached",
        editionLimitReached: value.editionLimitReached
    } : "alreadyOwned" in value ? {
        __kind__: "alreadyOwned",
        alreadyOwned: value.alreadyOwned
    } : "insufficientFunds" in value ? {
        __kind__: "insufficientFunds",
        insufficientFunds: value.insufficientFunds
    } : "success" in value ? {
        __kind__: "success",
        success: from_candid_CollectibleEdition_n12(_uploadFile, _downloadFile, value.success)
    } : "tokenNotFound" in value ? {
        __kind__: "tokenNotFound",
        tokenNotFound: value.tokenNotFound
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CollectibleEdition>): Array<CollectibleEdition> {
    return value.map((x)=>from_candid_CollectibleEdition_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Swarm>): Array<Swarm> {
    return value.map((x)=>from_candid_Swarm_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n21(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_Directionality_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Directionality): _Directionality {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MintCollectibleRequest_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MintCollectibleRequest): _MintCollectibleRequest {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tokenId: NodeId;
    tokenType: Variant_lawToken_interpretationToken;
}): {
    tokenId: _NodeId;
    tokenType: {
        lawToken: null;
    } | {
        interpretationToken: null;
    };
} {
    return {
        tokenId: value.tokenId,
        tokenType: to_candid_variant_n27(_uploadFile, _downloadFile, value.tokenType)
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    socialUrl?: string;
}): {
    name: string;
    socialUrl: [] | [string];
} {
    return {
        name: value.name,
        socialUrl: value.socialUrl ? candid_some(value.socialUrl) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_lawToken_interpretationToken): {
    lawToken: null;
} | {
    interpretationToken: null;
} {
    return value == Variant_lawToken_interpretationToken.lawToken ? {
        lawToken: null
    } : value == Variant_lawToken_interpretationToken.interpretationToken ? {
        interpretationToken: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Directionality): {
    none: null;
} | {
    bidirectional: null;
} | {
    unidirectional: null;
} {
    return value == Directionality.none ? {
        none: null
    } : value == Directionality.bidirectional ? {
        bidirectional: null
    } : value == Directionality.unidirectional ? {
        unidirectional: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
